* Chapter 5
** Introduction
- Efficiency: Are we getting the most that we can out of our scarce resources?
- Equity: Is what we're getting out of our resources fairly dstributed?
** Resource Allocation Methods
- Scarce resources might be allocated by
  - Market price
  - Command (government, organizations and their hierarchical structures, rations, etc.)
  - Majority rule
  - Contest
  - First come, first served
  - Lottery
  - Force
** Demand and Consumer Surplus
- Demand, Willingness to Pay, and Value
  - Value is what we get, price is what we pay
  - The value of one more unit of a good or service is its marginal benefit
  - The maxumum price that a person is willing to pay reveals marginal benefit
  - The demand curve is a marginal benefit curve
- Individual Demand and Market Demand
  - The relationship between the price of a good and the quantity demanded
    - by one person: individual demand
    - by all buyers in the market: market demand
  - The market demand curve is the horizontal sum of individual demand curves
- Consumer Surplus
  - the excess of the benefit recieved from a good over the amount paid for it
  - Calculate as the marginal benefit of a good - price, summed over quantity bought
  - Market consumer surplus is the sum of individual consumer surplus
** Supply and Producer Surplus
- Supply and Marginal Cost
  - To make a profit, firms must sell their output for a price > cost of production
  - Cost is what the producer gives up, price is what the producer recieves
- Supply, Marginal Cost, and Minimum Supply-Price
  - The cost of one more unit of a good or service is the marginal cost
  - The minimum price that a firm is willing to accept is its marginal cost
  - A supply curve is a marginal cost curve
- Producer surplus
  - The excess of the amount recieved from a sale over the cost of production
  - Calculate as price - marginal cost, summed over quantity
** Is the Market Efficient?
- Efficiency of Competitive Equilibrium
  - Resources are allocated efficienty when marginal social benefit = marginal social cost
  - If nobody other than producers and consumers are effected, the competitive equilibrium
    can allocate resources efficiently
** Underproduction and Overproduction
- Market failure occurs upon an inefficient outcome (overproduction or underproduction)
- Deadweight loss is the quantification of inefficiency by calculating the area of the 
  full triangle before or after the equilibrium on a marginal social benefit & cost curve
** Market Failure
- Sources of Market Failure:
  - Price and quantity regulations -> blocks price & production, leads to underproduction
  - Taxes and subsidies -> taxes lead to underproduction, subsidies lead to overproduction
  - Externalities -> a cost/benefot affecting someone other than seller/buyer, leads to either
    underproduction or overproduction
  - Public Goods and Common Resources
    - Public goods: benefit everyone, nobody can be excluded. Nobody wants to pay for a public
      good, leading to underproduction.
    - Common resouce: owned by nobody, but can be used by everyone. Leads to tragedy of the commons
      and overproduction
    - Monopoly -> self-interest to produce profits results in underproduction
    - High Transaction costs -> leads to underproduction
** Fairness
- Ideas of fairness can be divided into two rules
  - Not fair if the result isn't fair
    - Utilitarianism: greatest happiness for greatest number
  - Not far if the rules aren't fair
*** It's not Fair if the Results aren't Fair
- If everyone gets the same marginal utility from a given amount of income, and 
  if the marginal benefit of income decreases as income increases, then taking a dollar from a 
  richer person and giving it to a poorer person increases total benefit
- Only when income is equally distributed has the greatest happiness been achieved
- Utlitarianism ignores the cost of making income transfers
- Recognizing these costs leads to the big tradeoff between efficiency and fairness
*** It's not Fair if Rules aren't Fair
- Symmetry principle: the requirement that people in similar situation be treated similarly
- Nozick suggests that fairness is based on two rules
  - The state must create and enforce laws that establish/protect private property
  - Private property may be transferred form one person to another only by voluntary exchange
* Chapter 4
** Introduction to Elasticity
- closeness of substitutes is critical to understanding elasticity of supply and demand
** Elasticity of Demand
*** Calculting Elasticity of Demand
- Price elasticity of demand is a unit free measure of the responsiveness of quantity 
  demanded to a change in price when all other influences stay the same
- percentage change in quantity demanded/percentage change in price
- percent change in price is calculated as change in price/average of two goods/services
*** Inelastic and Elastic Demand
- Demand can be inelastic, unit elastic, or elastic
- Elasticity can range from 0 to infinity
- If quantity demanded doesn't change when the price changes, price elasticity = 0 and the good
  has perfectly inelastic demand (Vertical demand curve)
- If price elasticity equals exactly one, the good has unit elastic demand
- If price elasticity of demand is less than 1 then the good has inelastic demand
- If price elasticity is greater than 1, then the good has an elastic demand
- If the price elasticity is infinity, the good has a perfectly 
  elastic demand (Horizontal demand curve)
** Factors Influencing Elasticity of Demand
*** Closeness of substitutes
- the closer the substitutes, the more elastic the demand for a good or service
- necessities, such as food or housing, generally have an inelastic demands
- luxuries, such as exotic vacations, generally have elastic demand
*** Proportion of Income Spent on Good
- The greater the portion of income consumers spend on a good, the larger the elasticity of demand 
*** Time Elapsed Since Price Change
- The more time consumers have to adjust to a price change or the longer the good can be stored
  without losing its value, the more elastic the demand for the good
** Elasticity on a Linear Demand Curve & Total Revenue Test
- At the midpoint of a linear demand curve, demand is unit elastic
- At prices above the midpoint, demand is elastic
- At prices below the midpoint, demand is inelastic
*** Total Revenue and Elasticity
- Total revenue from the sale of a good or service = price of good * quantity sold
- Raising the price doesn't always increase total revenue
- If demand is elastic, a 1% price cut increases quantity sold by >1%, total revenue decreases
- If demand is inelastic, a 1% price cut increases the quantity <1%, total revenue decreases
- If demand is unit elastic a 1% price cut increases the quantity sold by 1%, total revenue same
*** Total Revenue Test
- a method of estimating the price elasticity of demand by
  observing the change in total revenue that results from a price change
- If a price cut increases total revenue, demand is elastic
- If price cut decreases total revenue demand is inelastic
- If a price cut doesn't change total revenue, demand is unit elastic
- On a bell curve, increase shows elastic, decrease shows inelastic, and peak is unit elastic
** Income Elasticity and Cross Elasticity of Demand
*** Income Elasticity
- Income elasticity of demand measures how the quantity demanded responds to a change in income
  - % change in quantity demanded/ % change in income
- If income elasticity is >1, demand is income elastic and the good is a normal good
- If the income elasticity is 0<x<1, demand is income inelastic and the good is normal elastic
- If income elasticity is <0, the good is an inferior good
*** Cross Elasticity of Demand
- Measure of the responsiveness of demand to change in the price of a substitute/complement 
  - % change in quantity demanded/ % change in price of substitute/complement
- Cross elasticity of demand is:
  - positive for a substitute
  - negative for a complement
** Elasticity of Supply
- Elasticity of supply: measures the responsiveness of quantity suppled to a change in price
  - % change in quantity supplied / % change in price
- Supply is perfectly inelastic when supply curve is vertical and elasticity = 0
- Supply is unit elastic if the supply curve is linear and passes through the origin 
- Supply is perfectly elastic when the supply curve is elastic and the elasticity = infinity
*** Factors Influencing Elasticity of Supply
- Depends on
  - Resource substitution possibilities
    - The easier it is to substitute among resources used, the greater the elasticity of supply
  - Time frame for supply decision
    - Momentary supply - perfectly inelastic for physical goods
    - Short-run supply is somewhat elastoc
    - Long-run supply is the most elastic
* Chapter 3
** Introduction
- Markets are any arrangements that enable buyers and sellers to get information
  and do business with each other
- Competitive Market: many buyers and many sellers so no single buyer or seller can
  influence prices
** Demand
- Reflects the buyers' side of the market
- If you demand something, you
  - want it
  - can afford it
  - have a definite plan to buy it
- Quantity demanded: amount that consumers plan to buy 
  during a particular time @ a particular price
- Law of Demand: other things remaining the same, the higher the price of a good, the smaller
  the quantity demanded (and vice versa)
- Substitution Effect: when the relative price of a good rises, people seek substitutes so
  the quantity demanded decreases
- When the price of a good rises relative to income, people cannot afford all the things
  they previously bought so quantity demanded decreases
- Demand Curve and Demand Schedule
  - the term demand refers to the entire relationship between good and quantity demanded
- Demand Curve: exhibits relationshit between quantity demanded and price when all other
  consumers' planned purchases remain constant
- Willingess and Ability to Pay
  - The smaller the quantity available, the higher the price someone is willing to pay for
    another unit
  - Willingness to pay measures marginal benefit
- Changes in Demand: when some influence on buying plans other than price changes, there is a
  shift in demand for that good
- 6 factors influencing demand:
  - Price of related goods
    - substitutes - good that can be used in place of another
    - complement - good that is used in conjunction with another
    - If $ substitute inc or $ complement dec, demand of good inc
    - if $ substitute dec or $ complement inc, demand of good dec
  - Expected future prices
    - if expected future price inc, current demand inc
    - if expected future price dec, current demand dec
  - Income
    - normal good: a good for which demand inc as income inc
    - inferior good: a good for which demand dec as income inc
    - if expected future income increases/credit is easier to get, current demand inc
  - Population
    - The higher the population, the higher the demand
  - Preferences
    - People with the same income have different demands if they have different preferences
** Supply
- If a firm is a supplier, they
  - have the resources and tech to produce it
  - can profit from producing it
  - has a definite plan to produce and sell it
- Quantity supplied: the amount producers plan to sell during a given time at a particular price
- Law of Supply: Other things remaning the same, the higher the price of a good, the greater the
  quantity supplied (and vice versa).
- Supply Curve and Supply Schedule
  - Minimum supply price: As quantity produced inc, marginal cost inc.
  - The lowest price at which someone is willing to sell an additional unit rises
  - This lowest price is called the marginal cost
- Changes in Supply
  - Increases in supply shifts the curve to the right (and vice versa)
- Factors that affect Supply
  - Prices of factors of production
    - If the price of an input inc, supply dec; curve shifts left
  - Prices of related goods produced
    - denoted by substitute for production, not just substitute
    - supply of a good inc if price of a substitute dec
    - complements in production: goods that must be produced together (beef & leather)
    - supply of a good inc if the price of a complement in production inc
  - Expected Future Prices
    - If expected future price inc, current supply dec
  - Number of Suppliers
    - as number of suppliers inc, supply inc
  - Technology
    - Advances in technology lower the cost of making existing products
    - inc in technology means inc in supply
  - State of Nature
    - natural forces and disasters can dec supply
** Equilibrium
- Equilibrium: a situation in which opposing forces balance each other
- Equilibrium Price: the price at which quantity demanded = quantity supplied
- Equilibrium Quantity: quantity bought and sold at equilibrium cost
- Price Regulation
  - Price regulates buying and selling plans
  - Price adjusts when plans don't match
- Price adjustments
  - Surplus forces prices down
  - Shortage forces prices up
- Increases in demand
  - When demand increases without changes in supply, shortages occur
  - Price therefore increaes
- Decrease in demand
  - At the original price, there is a surplus
  - Price therefore falls
- Increase in supply
  - At the original price, there is a surplus
  - Price therefore falls
- Decrease in supply
  - At the original price, there is a shortage
  - Price therefore increases
* Chapter 1
** Scarcity
- all economic questions arise because we want more than we can get
- inability to satisfy all wants because of scarcity
- scarcity = limited resources
** Definition of Economics
- because we face scarcity, we must make choices
- incentive = a reward that encourages an action or a penalty that discourages an action
- economics is the social science that studies the choices that individuals, businesses, etc.
 make as they cope with scarcity and the incentives that influence and reconcile those choices
- Economics divides into two parts:
  - Microeconomics = study of choices that individuals and businesses make & how those choices
    interact with markets and the influence of governments
  - Macroeconomics = the study of the performance of national and global economies
** 6 Key Ideas
- a choice is a tradeoff: ever choice is an exchange giving up one thing for another
- making a rational choice: a rational choice compares costs and benefits, maximizing benefit
- benefit = what you gain: the gain or pleasure something brings about, determined by preferences
  - preferences = what a person likes, dislikes, and the intensity of those feelings
- cost = what must be given up
   - opportunity cost = highest val alternative that must be given up
- choosing at the margin: the benefit of pursuing an incremental increase in some action
  is marginal benefit of that action
  - the opportunity cost of pursuing an incremental increase in some action is marginal cost
  - if marginal benefit > marginal cost, rational choice is to do more of that action
- choices respond to incentives: a change in marginal cost/benefit changes our incentives & choices
** Positive & Normative
- economists distinguish between two types of statements: 
  - positive statements: can be tested by checking the facts
  - normative statements: express an untestable opinion
- economists as social scientists
  - economists test economic models
  - economic model = a description of some aspect of the world w only the necessary features
- economists as policy advisors
** Resources & Highest Valued Use
- the scope of economics: 
  - how do choices end up determining "what, how, and for whom" goods and services get produced
- goods and services are produced using productive resources called factors of production
  - land
  - labor
  - capital
  - entrepreneurship
- who gets goods and services depends on income
  - land earns rent, labor earns wages, capital earns interest, entrepreneruship earns profit
- **resources gravitate towards their highest value use** 
** Self Interest & Social Interest
- self interest = choices that are made because you think they are the best for you
- social interest = choices that are best for society as a whole
- social interest has two dimensions: 
  - efficiency: resource use is efficient if it is not possible to make someone better off without
    making someone else worse off (no waste to be eliminated)
  - fair shares/equity: refers to the fairness with which resource division occurs in a society
- tension between self & social interest: information revolution, climate change, globalization
  
