* Chapter 11
** Introduction
- Decision timeframes
  - The firm makes many decisions to achieve profit maximization
  - 2 time frames: short run and long run
- The short run: a timeframe in which the quantity of one or more resources used in production is fixed. For most firms, the capital, called the firm's plant, is fixed in the short run. Other reousrces used by the firm (labor, raw materials, energy) can be changed in the short run
- The long run: a timeframe in which the quantities of all resources, including plant size, can be varied
- A sunk cost is a cost incurred by the firm that can't be changed
- Sunk costs are irrelevant to a firm's current decisions because the sunk cost can't be changed
** Short Run Tech Constraint
- To increase output in hte short run, a firm must increase amount of labor employed
- Marginal Product of Labor: change in the total product that results from a one-unit increase in the quantity of labor emplyed w all other inputers remaining the same
- Average product of labor = total product / quantity of labor employed
- Total product = total output
- As quantity of labor employed increases,
  - Total product increases
  - Marginal product increases initially but then decreases
  - Average product eventually decreases
  - Increasing marginal returns initially
  - Diminishing marginal returns eventually
- Increasing Marginal Returns
  - increased marginal returns arise from increased specialization and division of labor
  - Diminishing marginal returns arises because each additional worker has less access to capital and less space in which to work
- Law of Diminishing Returns: A firm uses more of a variable input within a given quantity of fixed inputs,the marginal product of variable input eventually diminishes
- Average Product Curve
  - When marginal product exceeds average product, average product increases
  - When marginal product is below average product, average product decreases
  - Average product will fall eventually because we know marginal product will fall over time as a result of the law of diminishing returns
  - When marginal product = average product, average product is at its maximum
** Costs in the Short Run
 - Three cost concepts and types of cost curves:
   - Total Cost
   - Marginal Cost
   - Average cost
- Total Cost (TC)
  - Cost of all resources used
  - Total Fixed Cost = cost of the firms fixed inputs, fixed costs don't change with output
  - Total Variable Cost = total cost of firm's variable inputs, var costs change with output
  - TC = Total fixed cost + total variable cost
- Average Cost
  - Average fixed cost = total fixed cost/unit of output
  - Average variable cost = total variable cost/unit of output
  - Average total cost = total cost/unit of output
  - Average cost = Average fixed cost + Average variable cost
- Marginal Cost (MC)
  - Marginal cost is the increase in total cost that results from a one unit increase in total product
  - Over the output range with increasing marignal returns, marginal cost falls as output increases
  - Over the output range with diminishing marginal returns, marginal cost rises as output increases
- The average fixed cost shows that average fixed cost falls as output increases
- The average variable cost is U shaped
  - As output increases, average variable cost falls to a minimum then increases
- Average Total Cost curve is also U-shaped because it is the sum of AVC and AFC
- Average total cost falls at first because of
  - Decreased fixed cost with more output
  - Specialization and division of labor
- ATF will keep falling for some time after AVC starts rising because of AFC continuing to fall. Eventually, AVC gets larger and AFC falls only a little, bringing ATC higher
- Marginal Cost curve passes through the minimums of AVC and ATC curves
- For outputs over which AVC is falling, MC is below AVC
- For outputs over which AVC is rising, MC is above AVC
- For the output at minimum AVC, MC = AVC
- For outputs over which ATC is rising, MC is above ATC; For outputs over which ATC is decreasing, MC is below ATC
- For output at minimum ATC, MC = ATC
*** Summary
- ATC curve is the vertical sum of AFC and AVC
- The U shape of ATC comes because of
  - Spreading total fixed cost over a larger output (AFC slopes downward)
  - Eventually diminishing returns from the U shaped AVC curve
** Shifts in the Cost Curves
 - Two factors can shoft a firm's cost curves
   - Technology: relationship between inputs and outputs
     - Technology can change both product and cost curves
     - Increase in productivity shifts product curve upward, cost curve downward
     - Tech advance usually results in using more capital and less labor, fixed costs     increase and var costs decrease
   - Prices of Factos of Production
     - An increase in the price of a factor of production increases costs and shifts cost curves
     - An increase in fixed cost shifts TC and ATC curves upward
     - An increase in variable cost shifts the TC, ATC, AVC, and MC
** Costs in the Long Run
* Chapter 6
** Price Ceiling 
- Price ceiling or price cap is a regulation that makes it illegal to charge higher than a 
  specified level
- Price ceilings applied to a housing market is called a rent ceiling
- If the rent ceiling is above equilibrium rent, it has no effect. 
 A rent ceiling set below the equilibrium creates
  - A housing shortage
  - Increased search activity
  - Black Market
  - Occurs because the legal price cannot eliminate the shortage and other mechanisms take over
- Increased search activity: the time spent looking for someone with whom to do business activity
  - Opp. cost of housing = rent (regulated) + opp cost of search activity (unregulated)
  - The opportunity cost of housing can exceed unregulated rent (cost is higher than equilibrium)
- A Black Market: An illegal market that operates alongside a legal market in which a price ceiling
  or other restriction has been imposed.
- Rent Ceiling Inefficiency
  - A rent ceiling below equilibrium leads to inefficient underproduction
  - Rent ceiling decreases quantity suppled to less than efficient quantity
  - Marginal social benefit exceeds Marginal cost and deadweight loss occurs
- Are Rent Ceilings Fair
  - According to fair rules, rent ceilings are unfair because they block voluntary exchange
  - According to fair results, a rent ceiling is unfair because it doesn't usually benefit the poor
  - Allocation methods:
    - Lower willingness to pay search costs
    - Lottery, doesn't help the poor more than others
    - First come, first served
    - Discrimination
** Price Floor
- A price floor is a regulation that makes it illegal to trade at a price lower than a specific lvl
- Price floor applied to labor market = minimum wage
- Price floors below the equilibrium have no effect
- If minimum wage is above equilibrium wage, quantity of labor supplied exceeds quantity demanded
  by employers, creating a suprlus of labor
- Because the legal wage rate can't eliminate surplus, this causes unemployment
- Inefficency of a Minimum Wage
  - Supply of labor measures the social cost of labor to workers
  - The demand for labor measures its marginal social benefit
  - A minimum wage above equilivium wage decreases the quantity of labor emplyed
  - Deadweight loss arises with potential loss from increased job search costs
- Ultimately, both this price floor and price ceilings lead to underproduction
- Is Minimum Wage Fair?
  - Currently 7.25, same since 2009
  - Many economists believe that min wage rates increase unemployment of young, low-skilled workers
** Taxes
*** Tax Incidence
- Tax incidence is the division of the burden of a tax between buyers and sellers
- When an item is taxes, the price might rise by the full amount of the tax, by a lesser amount,
  or not at all
- If market price rises by the full amount of the tax, the buyer pays the tax
- If the market rises by a lesser amount than the tax, the buyer and seller share the tax burden
- If the market price doesn't change, sellers pay the tax
*** Equivalence of a Tax on Buyers and Sellers
- The effect of a tax is the same, regardless of which side of the market the tax is imposed upon
- Demand decreases (moves down), Supply decreases (moves up), overall always decreasing quantity
- Price paid by buyers is always higher than price recieved by sellers
- Price paid by buyers is always on the original demand curve, price paid by sellers is 
  always on the original supply curve
- With no tax, marginal social benefit = marginal social cost, maximizing surplus
- Taxes decrease quantity, raising buyer's price and lowering seller's cost
- Tax revenue takes part of the total surplus
*** Tax Incidence and Elasticity
- The more inelastic the demand, the larger the buyers' share of the tax
  - Perfectly inelastic: buyer pays full tax
  - Perfectly elastic: seller pays full tax
- The more inelastic the supply, the larger the sellers' share of the tax
  - Perfectly inelastic supply: seller pays the full tax
  - Perfectly elastic: buyer pays the full tax
*** Taxes in Practice
- Taxes are usually levied on goods and services w inelastic demand or inelastic supply
- Alcohol, tobacco, and gasoline have inelastic demand, so buyers pay most of the tax
- Labor has inelastic supply, so sellers usually pay most of the tax
*** Taxes and Fairness
- Benefits Principle: People should pay taxes equal to the benefits they recieve from the govt
- Ability-to-Pay Principle: People should pay taxes based on how easily they can bear the tax
** Quotas and Subsidies
- Quota: an upper limit to the quantity of a good that may be produced during a specified period
- Subsidy: a payment made by the government to a producer
- Quotas help protect producers to create a profit when the market isn't doing well
- Quotas make production inefficient and producers have an incentive to cheat
** Markets for Illegal Goods
*** Penalties
- Penalties on sellers has the same effect of a tax on the seller
- Supply of the good decreases to penalty * cost of being caught + marginal cost 
  - Supply + Cost of Breaking the Law
- Penalty on buyers = Demand - cost of breaking the law
- Opportunity cost increases
- Penalties on both buyers and sellers is the intersection of S+CBL and D-CBL
- The new market price is P(c), buyer pays P(b) and seller gets P(s)
*** Legalizing and Taxing Drugs
- An illegal good can be legalized and taxed
- A high enough tax rate decreases consumption to the level that occurs when trade is illegal
* Chapter 5
** Introduction
- Efficiency: Are we getting the most that we can out of our scarce resources?
- Equity: Is what we're getting out of our resources fairly dstributed?
** Resource Allocation Methods
- Scarce resources might be allocated by
  - Market price
  - Command (government, organizations and their hierarchical structures, rations, etc.)
  - Majority rule
  - Contest
  - First come, first served
  - Lottery
  - Force
** Demand and Consumer Surplus
- Demand, Willingness to Pay, and Value
  - Value is what we get, price is what we pay
  - The value of one more unit of a good or service is its marginal benefit
  - The maxumum price that a person is willing to pay reveals marginal benefit
  - The demand curve is a marginal benefit curve
- Individual Demand and Market Demand
  - The relationship between the price of a good and the quantity demanded
    - by one person: individual demand
    - by all buyers in the market: market demand
  - The market demand curve is the horizontal sum of individual demand curves
- Consumer Surplus
  - the excess of the benefit recieved from a good over the amount paid for it
  - Calculate as the marginal benefit of a good - price, summed over quantity bought
  - Market consumer surplus is the sum of individual consumer surplus
** Supply and Producer Surplus
- Supply and Marginal Cost
  - To make a profit, firms must sell their output for a price > cost of production
  - Cost is what the producer gives up, price is what the producer recieves
- Supply, Marginal Cost, and Minimum Supply-Price
  - The cost of one more unit of a good or service is the marginal cost
  - The minimum price that a firm is willing to accept is its marginal cost
  - A supply curve is a marginal cost curve
  - The market supply curve is the horizontal sum of the individual supply
  curves and is formed by adding the quantities supplied by all the producers at each price.
- Producer surplus
  - The excess of the amount recieved from a sale over the cost of production
  - Calculate as price - marginal cost, summed over quantity
** Is the Market Efficient?
- Efficiency of Competitive Equilibrium
  - Resources are allocated efficienty when marginal social benefit = marginal social cost
  - If nobody other than producers and consumers are effected, the competitive equilibrium
    can allocate resources efficiently
** Underproduction and Overproduction
- Market failure occurs upon an inefficient outcome (overproduction or underproduction)
- Deadweight loss is the quantification of inefficiency by calculating the area of the 
  full triangle before or after the equilibrium on a marginal social benefit & cost curve
** Market Failure
- Sources of Market Failure:
  - Price and quantity regulations -> blocks price & production, leads to underproduction
  - Taxes and subsidies -> taxes lead to underproduction, subsidies lead to overproduction
  - Externalities -> a cost/benefot affecting someone other than seller/buyer, leads to either
    underproduction or overproduction
  - Public Goods and Common Resources
    - Public goods: benefit everyone, nobody can be excluded. Nobody wants to pay for a public
      good, leading to underproduction.
    - Common resouce: owned by nobody, but can be used by everyone. Leads to tragedy of the commons
      and overproduction
    - Monopoly -> self-interest to produce profits results in underproduction
    - High Transaction costs -> leads to underproduction
** Fairness
- Ideas of fairness can be divided into two rules
  - Not fair if the result isn't fair
    - Utilitarianism: greatest happiness for greatest number
  - Not far if the rules aren't fair
*** It's not Fair if the Results aren't Fair
- If everyone gets the same marginal utility from a given amount of income, and 
  if the marginal benefit of income decreases as income increases, then taking a dollar from a 
  richer person and giving it to a poorer person increases total benefit
- Only when income is equally distributed has the greatest happiness been achieved
- Utlitarianism ignores the cost of making income transfers
- Recognizing these costs leads to the big tradeoff between efficiency and fairness
*** It's not Fair if Rules aren't Fair
- Symmetry principle: the requirement that people in similar situation be treated similarly
- Nozick suggests that fairness is based on two rules
  - The state must create and enforce laws that establish/protect private property
  - Private property may be transferred form one person to another only by voluntary exchange
* Chapter 4
** Introduction to Elasticity
- closeness of substitutes is critical to understanding elasticity of supply and demand
** Elasticity of Demand
*** Calculting Elasticity of Demand
- Price elasticity of demand is a unit free measure of the responsiveness of quantity 
  demanded to a change in price when all other influences stay the same
- percentage change in quantity demanded/percentage change in price
- percent change in price is calculated as change in price/average of two goods/services
*** Inelastic and Elastic Demand
- Demand can be inelastic, unit elastic, or elastic
- Elasticity can range from 0 to infinity
- If quantity demanded doesn't change when the price changes, price elasticity = 0 and the good
  has perfectly inelastic demand (Vertical demand curve)
- If price elasticity equals exactly one, the good has unit elastic demand
- If price elasticity of demand is less than 1 then the good has inelastic demand
- If price elasticity is greater than 1, then the good has an elastic demand
- If the price elasticity is infinity, the good has a perfectly 
  elastic demand (Horizontal demand curve)
** Factors Influencing Elasticity of Demand
*** Closeness of substitutes
- the closer the substitutes, the more elastic the demand for a good or service
- necessities, such as food or housing, generally have an inelastic demands
- luxuries, such as exotic vacations, generally have elastic demand
*** Proportion of Income Spent on Good
- The greater the portion of income consumers spend on a good, the larger the elasticity of demand 
*** Time Elapsed Since Price Change
- The more time consumers have to adjust to a price change or the longer the good can be stored
  without losing its value, the more elastic the demand for the good
** Elasticity on a Linear Demand Curve & Total Revenue Test
- At the midpoint of a linear demand curve, demand is unit elastic
- At prices above the midpoint, demand is elastic
- At prices below the midpoint, demand is inelastic
*** Total Revenue and Elasticity
- Total revenue from the sale of a good or service = price of good * quantity sold
- Raising the price doesn't always increase total revenue
- If demand is elastic, a 1% price cut increases quantity sold by >1%, total revenue decreases
- If demand is inelastic, a 1% price cut increases the quantity <1%, total revenue decreases
- If demand is unit elastic a 1% price cut increases the quantity sold by 1%, total revenue same
*** Total Revenue Test
- a method of estimating the price elasticity of demand by
  observing the change in total revenue that results from a price change
- If a price cut increases total revenue, demand is elastic
- If price cut decreases total revenue demand is inelastic
- If a price cut doesn't change total revenue, demand is unit elastic
- On a bell curve, increase shows elastic, decrease shows inelastic, and peak is unit elastic
** Income Elasticity and Cross Elasticity of Demand
*** Income Elasticity
- Income elasticity of demand measures how the quantity demanded responds to a change in income
  - % change in quantity demanded/ % change in income
- If income elasticity is >1, demand is income elastic and the good is a normal good
- If the income elasticity is 0<x<1, demand is income inelastic and the good is normal elastic
- If income elasticity is <0, the good is an inferior good
*** Cross Elasticity of Demand
- Measure of the responsiveness of demand to change in the price of a substitute/complement 
  - % change in quantity demanded/ % change in price of substitute/complement
- Cross elasticity of demand is:
  - positive for a substitute
  - negative for a complement
** Elasticity of Supply
- Elasticity of supply: measures the responsiveness of quantity suppled to a change in price
  - % change in quantity supplied / % change in price
- Supply is perfectly inelastic when supply curve is vertical and elasticity = 0
- Supply is unit elastic if the supply curve is linear and passes through the origin 
- Supply is perfectly elastic when the supply curve is elastic and the elasticity = infinity
*** Factors Influencing Elasticity of Supply
- Depends on
  - Resource substitution possibilities
    - The easier it is to substitute among resources used, the greater the elasticity of supply
  - Time frame for supply decision
    - Momentary supply - perfectly inelastic for physical goods
    - Short-run supply is somewhat elastoc
    - Long-run supply is the most elastic
* Chapter 3
** Introduction
- Markets are any arrangements that enable buyers and sellers to get information
  and do business with each other
- Competitive Market: many buyers and many sellers so no single buyer or seller can
  influence prices
** Demand
- Reflects the buyers' side of the market
- If you demand something, you
  - want it
  - can afford it
  - have a definite plan to buy it
- Quantity demanded: amount that consumers plan to buy 
  during a particular time @ a particular price
- Law of Demand: other things remaining the same, the higher the price of a good, the smaller
  the quantity demanded (and vice versa)
- Substitution Effect: when the relative price of a good rises, people seek substitutes so
  the quantity demanded decreases
- When the price of a good rises relative to income, people cannot afford all the things
  they previously bought so quantity demanded decreases
- Demand Curve and Demand Schedule
  - the term demand refers to the entire relationship between good and quantity demanded
- Demand Curve: exhibits relationshit between quantity demanded and price when all other
  consumers' planned purchases remain constant
- Willingess and Ability to Pay
  - The smaller the quantity available, the higher the price someone is willing to pay for
    another unit
  - Willingness to pay measures marginal benefit
- Changes in Demand: when some influence on buying plans other than price changes, there is a
  shift in demand for that good
- 6 factors influencing demand:
  - Price of related goods
    - substitutes - good that can be used in place of another
    - complement - good that is used in conjunction with another
    - If $ substitute inc or $ complement dec, demand of good inc
    - if $ substitute dec or $ complement inc, demand of good dec
  - Expected future prices
    - if expected future price inc, current demand inc
    - if expected future price dec, current demand dec
  - Income
    - normal good: a good for which demand inc as income inc
    - inferior good: a good for which demand dec as income inc
    - if expected future income increases/credit is easier to get, current demand inc
  - Population
    - The higher the population, the higher the demand
  - Preferences
    - People with the same income have different demands if they have different preferences
** Supply
- If a firm is a supplier, they
  - have the resources and tech to produce it
  - can profit from producing it
  - has a definite plan to produce and sell it
- Quantity supplied: the amount producers plan to sell during a given time at a particular price
- Law of Supply: Other things remaning the same, the higher the price of a good, the greater the
  quantity supplied (and vice versa).
- Supply Curve and Supply Schedule
  - Minimum supply price: As quantity produced inc, marginal cost inc.
  - The lowest price at which someone is willing to sell an additional unit rises
  - This lowest price is called the marginal cost
- Changes in Supply
  - Increases in supply shifts the curve to the right (and vice versa)
- Factors that affect Supply
  - Prices of factors of production
    - If the price of an input inc, supply dec; curve shifts left
  - Prices of related goods produced
    - denoted by substitute for production, not just substitute
    - supply of a good inc if price of a substitute dec
    - complements in production: goods that must be produced together (beef & leather)
    - supply of a good inc if the price of a complement in production inc
  - Expected Future Prices
    - If expected future price inc, current supply dec
  - Number of Suppliers
    - as number of suppliers inc, supply inc
  - Technology
    - Advances in technology lower the cost of making existing products
    - inc in technology means inc in supply
  - State of Nature
    - natural forces and disasters can dec supply
** Equilibrium
- Equilibrium: a situation in which opposing forces balance each other
- Equilibrium Price: the price at which quantity demanded = quantity supplied
- Equilibrium Quantity: quantity bought and sold at equilibrium cost
- Price Regulation
  - Price regulates buying and selling plans
  - Price adjusts when plans don't match
- Price adjustments
  - Surplus forces prices down
  - Shortage forces prices up
- Increases in demand
  - When demand increases without changes in supply, shortages occur
  - Price therefore increaes
- Decrease in demand
  - At the original price, there is a surplus
  - Price therefore falls
- Increase in supply
  - At the original price, there is a surplus
  - Price therefore falls
- Decrease in supply
  - At the original price, there is a shortage
  - Price therefore increases
* Chapter 2
** Production Possibilities Frontier
- PPF is the boundary between combinations of goods and services that can and can't be prodiced
- Points outside the PPF are unattainable
*** Production Efficiency
- We can achieve production efficiency if we cannt make more of one good without making les
  of another such good.
- All points on the PPF are efficient, while all points within the PPF are inefficient
** Opportunity Cost on the PPF
- Every choice/movement along the PPF is an opportunity cost
- Opportunity Cost = Amnt given up/Amnt gained
- Opportunity cost increases as we move along the PPF
  - Because resources are not equally productive for all activities, the PPF bows outwards
  - The outward bow of the PPF means that as the quantity of each good increases, so does 
    the opportunity cost
** Marginal Costs
- Marginal Cost: The opportunity cost of producing one more unit of that good
- Marginal Cost curve slopes upward for the same reason that the PPF bows outward
** Marginal Benefits
- Preferences: A description of a person's likes and dislikes
- Marignal benefit: the benefit recieved from consuming one more unit of that good
- Marginal benefot is measured by the amount that a person is willing to pay for one more unit
  of a particular good or service
- Principle of Decreasing Marginal Benefit: The more we have of any good, the smaller the marginal
  benefit of that good
** Allocative Efficiency
- When we cannot produce more of any one good without giving up some other good that we value
  more highly
- Point at which marginal cost and marginal benefit curve meet
** Comparative & Absolute advantage
- Comparative advantage: When a person can perform an activity at a lower opportunity cost than
  anyone else
- Absolute advantage: When a person is more productiv than others
** Economic Growth
- Two key factors:
  - Technnological Change
  - Capital accumulation (growth of capital resources)
- Economic growth is not free, investing in tech and capital costs production today but helps
  production tomorrow through smart investment
** Cricular Flow Model
- Need:
  - Firms (take input, make output)
  - Markets
  - Property Rights
  - Money
* Chapter 1
** Scarcity
- all economic questions arise because we want more than we can get
- inability to satisfy all wants because of scarcity
- scarcity = limited resources
** Definition of Economics
- because we face scarcity, we must make choices
- incentive = a reward that encourages an action or a penalty that discourages an action
- economics is the social science that studies the choices that individuals, businesses, etc.
 make as they cope with scarcity and the incentives that influence and reconcile those choices
- Economics divides into two parts:
  - Microeconomics = study of choices that individuals and businesses make & how those choices
    interact with markets and the influence of governments
  - Macroeconomics = the study of the performance of national and global economies
** 6 Key Ideas
- a choice is a tradeoff: ever choice is an exchange giving up one thing for another
- making a rational choice: a rational choice compares costs and benefits, maximizing benefit
- benefit = what you gain: the gain or pleasure something brings about, determined by preferences
  - preferences = what a person likes, dislikes, and the intensity of those feelings
- cost = what must be given up
   - opportunity cost = highest val alternative that must be given up
- choosing at the margin: the benefit of pursuing an incremental increase in some action
  is marginal benefit of that action
  - the opportunity cost of pursuing an incremental increase in some action is marginal cost
  - if marginal benefit > marginal cost, rational choice is to do more of that action
- choices respond to incentives: a change in marginal cost/benefit changes our incentives & choices
** Positive & Normative
- economists distinguish between two types of statements: 
  - positive statements: can be tested by checking the facts
  - normative statements: express an untestable opinion
- economists as social scientists
  - economists test economic models
  - economic model = a description of some aspect of the world w only the necessary features
- economists as policy advisors
** Resources & Highest Valued Use
- the scope of economics: 
  - how do choices end up determining "what, how, and for whom" goods and services get produced
- goods and services are produced using productive resources called factors of production
  - land
  - labor
  - capital
  - entrepreneurship
- who gets goods and services depends on income
  - land earns rent, labor earns wages, capital earns interest, entrepreneruship earns profit
- **resources gravitate towards their highest value use** 
** Self Interest & Social Interest
- self interest = choices that are made because you think they are the best for you
- social interest = choices that are best for society as a whole
- social interest has two dimensions: 
  - efficiency: resource use is efficient if it is not possible to make someone better off without
    making someone else worse off (no waste to be eliminated)
  - fair shares/equity: refers to the fairness with which resource division occurs in a society
- tension between self & social interest: information revolution, climate change, globalization
  
