* 08.31.20
** Human Populations
- 3 major sparks of growth
  - Agricultural Revolution
  - Industrual Revolution
  - Green Revolution
- With more food and technology, the population and need for more human labor increased
- The human population is rapidly increasing and the impact of humans is due to:
  - More humans overall
  - Greater growth / person
- To address population growth, we need to pursue a variety of approaches that address factors
  encouraging high birth rates
- Zero population growth: the absence of population growth, occurs when birth rates = death rates
  - Replacement fertility is reached
** Population Ecology
- Analyze and categorize human populations using population ecology techniques
- Population Ecology: a branch of biology dealing with the number of individuals
  in a particular species in an area over time
- Ecologists study populations to understand what makes them survive and thrive
- Size, distribution, and growth rate is influenced by a variaty of factors and are important to 
  understanding popilation ecology
** Monitoring Population Dynamics
- Population Dynamics: Changes over time in population size and composition
- Important metrics:
  - Minimum viable population - min number of individuals that would still allow population to persist or grow
  - Carrying Capacity (K) - the maximum population size that a particular environment can support indefinitely
- Population Density - the overall desnity a particular populaiton can sustain
** Exponential Growth & Populations
- Exponential growth occurs in populations when growth is unrestricted. This is, overall, unsustainable
- Growth which becomes progressively larger each breeding cycle
- Produces a J curve when plotted
** Monitoring Population Growth
- Population growth rate - the rate at which a population of a species grows over time
- Growth factors - factos which assist in the growth of a population
- Resistance factors - factors which inhibit the growth of a population
- Limiting factos: resources needed for survival but that may be in short supply
** Logistic Growth
- Occurs when a population nears carrying capacity (k) 
  - Maximum sustainable population size
  - Determined by limiting factors
** Density-dependent/ Density-independent Factors
- Density dependent factors increase as populations grow, typically biotic
  - Disease
  - Competition
  - Predation
- Density independent facts affect population growth regardless of population size
  - Storm
  - Fire/Flood
  - Avalanche
** Regulation
- Tendency for populations to decrease in size when above acertain level, and increase
  in size below that level
- Populations can only be regulated by density-dependent factors
- Top down Regulation
  - Predation
  - Disease
- Bottom up Regulation
  - Nutrients
  - Water
  - Sunlight
* 08.28.20
** What is Science?
- Science: a body of knowledge that allows us to understand the world around us
- Science is based on empirical evidence
- Science allows us to test our ideas and evaluate the evidence
- Scientific knowledge, including facts, theories, and laws, is subject to change
- Scientific claims change as new evidence is made available
** White-Nose Syndrome Case Study
*** About WNS
- White-Nose Syndrome
  - 2007-2016, 6+ million bats dead as a result of White Nose Syndrome
  - The reason for the deaths was White-Nose Syndrome
- Chytridiomycosis
  - Infectious, fungal disease affecting amphibians
  - Helped understand white-nose syndrome with bats
*** Science with WNS
- Scientific Method: the procedure used to empirically test a hypothesis
  1. Observations generate questions
  2. Choose a question to investigate
  3. Consult literature
  4. Develop a hypothesis and make a testable prediction
  5. Design and carry out a study
  6. Analyze data
  7. Draw a conclusion
- Inferences: Conclusions drawn based on observations
- Hypothesis: An inference that proposes possible explanation that includes previous knowledge/observation
- Testing a Hypothesis: Hypotheses can be tested through an observational or experimental study
- Scientific Studies: A fair test with results that could support or falsify the research prediction
  - Experimental Studies: Conditions are manipulated intentionally
    - Test Group: the group in an experimental study such that it differs from the control in only one way
    - Control Group: the group in an experimental study to which the test group's results are compared 
  - Observational Studies: Gather real-world data without any intentional variable manipulation
- Theory: A hypothesis that survives repeated testing by significant research can become a theory
- Correlation v Causation
  - Correlation: two things occuring together but not necessarily having a cause-effect relationship
  - Cause-Effect Relationship: the associationof a two variables that identifies one variable occurring
    as a result of the other
  - Observational studies can derive correlation but not causation
  - Experimental studies can derive causational relationships
- Policy: a formalized plan that addresses a desired outcome or goal
  - policies need to be flexible, adapt to new findings, address the environmental problem, fit social need
    and be economically viable in order to work effectively.
** Summary
- Scientific knowledge, through reliable and durable, is never absolute pr certain
- This knowledge, including facts, theories, and laws, is subject to change
- Physical evidence, systematically collected and logically analyzed, helps scientists
  understand environmental issues and guide policy decisions
* 08.25.20
** Applied v Empirical Science
- Applied Science = research whose findings are used to solve practical problems
- Empirical science: A scientific approach that investigates the natural world through case studies
** Social Traps
- Occurs when a large amount of people are using a shared resource
- Seem good in the short term but are actually bad in the long term
- 3 Types:
  - Tragedy of the Commons: When resources are shared, individuals try to maximize personal
    benefit which hurts the resource itself
  - Time delay: Collective decisions that are good today but gone tomorrow
  - Sliding reinforcer: related to the evolution of natural organisms and GMOs
** Beginning with Data Interpretation 
- Variables represent factors that can be manipulated, controlled, or merely measured for research
- Variation = how much a variable changes
- Independent var is controlled to see effects in the Dependent var
- Graphs explore relationships with data and report this data
** Observational v Experimental Studies
- Observational studies can observe a correlation but are unable to derive a causational reln.
- Experimental studies have a control var (required) and are able to derive causactional rlns.
* 08.24.20
** Definitions
- Ecology: the branch of science dealing with the relationships of living things to one another & the environment
- Environmental Science: The study of all aspects of the environment, including physical, chemical, and biological factos, particularly with respect to how these aspects affect humans, and vice versa
- Environmental Ethics: Personal philosophy that influences how a person interacts with their natural environment and thus influences how one responds to environmental problems
** Ecology != Environmentalism
- Distinguish between envrironmentalism & ecology

| Environmentalism                    | Ecology                                          |
|-------------------------------------+--------------------------------------------------|
| Activism to protect the environment | Scientific study of living and non-living things |
