* 12.09.20
** Wicked Problems
- Interconnected, complex problems that are very difficult to solve because of the multitude of opinions and effects they have
- Scientific knowledge is reliable and durable but it is never absolute or certain
** Spheres of Influence
- Economy -> Community -> Environment
- Economy is a social construct that exists within the community which resides inside on an environment
** Sustainable Living
- Need to meet the needs of today without compromising the needs of future generations
- Must be belowing carrying capacity and live a sustainable lifestyle
** Weather v Climate
- Weather: Conditions of atmosphere at a particular time/place
- Climate: Longer term than weather
** Keeling Curve
- Measure atmospheric CO2 from the Monnoloah observatory, showed increasing CO2 causing increased global warming and lower oceanwater PH
** Storm and Hurricane Intensification
- Climate change leading to a significant increase in weather and climate disasters
- Such disasters are extremely troublesome because of their impact on lives and economics
** Antibiotics
- Development of antibiotic resistance through natural selection
- Overuse of antibiotics in both humans and animals
- Natural selection results in changes in gene frequencies
  - Some individuals are more successful at obtaining resources, are able to produce more offspring
- Evolution: Changes in the heritable traits of a population of organisms as successive generations continue
- Increased connectivity will increase the rate and speed at which diseases are transmitted across the world.
** Freshwater
- Need approx 50l. to survive per day
- Not evenly distributed across the world
- Found mostly in aquifers
- Cannabis industry having a significant impact on social, cultural, economic, and environmental issues
-
* 12.07.20
** EROEI Ratio
- A measure of the net energy from an energy source
- Energy in the source - the energy required to get it, process it, ship it, and use itself
** Wicked Problem
- How to best meet our future energy needs is a wicked problem
- We need abundant, reliable energy sources to power our societies but many choices have significant problems
- No single sustainable energy source can replace fossil fuels, but together, the wide variety of energy sources at our disposal can
- Efforts should focus on aquiring a variety of domestic sources of energy and reducing energy needs
** Global Renewable Energy Consumption
- 57% Hydro
- 23% Biomass
- 9% Solar
- 7% Wind
** Biomass Fuels
- Bioenergy: energy contained in firewood and other plant matter
- Derived from solar energy
- Traditional direct fuels- wood, charcoal, animal dung
- Indirect fuels: food crops, crop waste, forestry waste
- 3 types of energy:
  - Heat
  - Electricity
  - Biofuels such as biodiesel
*** Biofuel advantages:
  - Carbon neutral
  - Lower carbon footprint than fossil fuels
  - Lower NO and SO
  - Abundant
  - Producted domestically, increasing energy independence
*** Biofuel Disadvantages
- Is it really carbon neutral?
- Cost of transport processing, fertilizers, water, etc.
- Clearing land for crops releases CO2
*** Cellulosic Ethanol v Starch Ethanol
- Ethanol is usually made from starch found in corn and similar high surgar crops
  - Yeasts easily ferment these sugars and produce ethanol as a by-product
- Making ethanol from cellulose is more difficult
  - Cellulose in grasses is not easily degraded
  - Very few species have the ability to digest it
** Wind Power
*** Advantages
- No fuel needed
- No pollutants released
- Domestic energy source
- Not subject to disruptions of single energy plants
*** Disadvantages
- Expensive
- Bird and Bat deaths (may interfere with bird movement corridors)
- Aesthetics
- Intermittent winds
- Windy areas not generally near urban areas
*** General
- 2/3 of wind power in the US: Texas, Cali, Iowa, Minnesota, Washington
- Wind Farms: clusters of turbines
- Currently produce < 0.5% of global electricity needs
- ~6% of the total renewable energy
- Fastest growing renewable sector
- Conservation and Innovation can be profitable
  - Denmark produces 20% of their electricity through wind power
  - Projected to increase to 50% by 2030
  - Denmark commands 60% of global makret for wind turbines
** Hydropower
- Capturing the energy of water moving under the force of gravity
- Supplies more lectricity than any other single renewable resource
- Generates 7% of electricity in the US, 17% around the world
- Most hydroelectric power generated by large plants within dams
*** Advantages
- Fossil fuels not needed
- No pollutants
- Energy cheap to produce
- Power produced can be matched to demand
- Dams also used for flood control
- Water retention
*** Disadvantages
- Effect on environment and human communities
- Ecosystem alteration and flow changes
- Peak flows no longer seasonal
- Sediment accumulation and transport altered
- Temperature and oxygen in stream changed
*** General
- Countries producing most hydroelectric power: China, Brazil, Canada, US, Russia, Norway, India (in order highest to lowest)
** Solar Energy
- Photovoltaic (PV) Cell
- Small fraction of power, although PV cell production growing by 25% per year
- Currently inefficient energy storage mechanism
- Low rainfall and limited cloud cover make the SW US an ideal region for solar power usage
*** Advantages
- Free and renewable
- No emissions
- Roof installations/More space options
- Jobs in the sector increasing 35%/year
*** Disadvantages
- High start up costs (10,000-20,000 for home to save hundreds of dollars per year)
- High cost of electricity compared to coal produced electricity
- Daylight requirements
- Geograohical limitations: solar energy unevenly distributed
- Hazardous materials used in construction
** Geothermal Energy
- Heat energy generated and stored in Earth
- Energy does not originate in the sun
- In a dry-steam power plant, underground hot water and steam used to generate electricity
*** Advantages
- Reliable and inexpensive
- Pollution free
- Uses 30-70% less energy than conventional methods
*** Disadvantages
- Ecosystem disturbance
- Replenishment rates of ground heat
- High startup costs
- Geographic limitations
** Ocean Energy
- Using kinetic energy of tides and waves
*** Advantages
- Renewage and pollution free
- Low cost of production
*** Disadvantages
- Ecosystem disturbance
- Tidal barrage systems need high tide amplitude
- Geographic limitations
** The Path Forward
- One recurring theme with renewable enrgy is that they are more expensive than fossil fuels
- Important to ask why fossil fuels are so cheap, need to consider all costs of these technologies
- When true cost is factored in, fossil fuels have highest external costs
- No single fuel can replace fossil fuels but a wide variety of options are available and considering more renewable sources is an important part of the solution
- More likely to meet energy needs with a wide variety of renewable technologies that fit each locale
* 12.04.20
** Locust Outbreaks
- What triggers locust outbreaks?
  - Locust outbreaks are caused by excessive rain, contributing to a moist area
  - Recent cyclones have contirbuted to very high amounts of recent rainfall
- Why are they so devastating?
  - A single locust can eat their own body weight (2g) per day, multiplied by the millions of locusts that comprise a single swarm
- What can be done to help control outbreaks?
  - Loud noises and preventing the locusts from laying their eggs is critical
  - Pesticide application and swarm location identification through an application
** Small Scale Farming and Food Security
 - Progress requires creating opportunities for innovation and entrepreneurship
 - Increased public research and extension investment
 - Small scale sustainability poses challenging policy choices: payment for ecological services, decentralized governance systems, and technology choices
** Economics and the Environment
- Economics isn't just about money, it is also about the environmental resources we depend on
  - Economics: the social science that deals with the production, distribution, and consumption of goods and services
- Environmental resources include ecosystem services
  - Ecosystem services: essential ecological processes that make life on Earth possible
- Environmental economists argue that mainstream economics will fail in the long run because it makes some assumptions that are inconsistent with the way nature operates.
- When the price of a product doesn't reflect the external social and environmental costs, those costs are paid by people other than the consumer. Internalizing external costs better reflects the true cost of a product
- Many US industries can't exist without illegal immigrants
- Undocumented immigrants make up more than half of hired labors on farms, 15% of construction workforce, 5% of total workforce
** The Great Climate Migration
- As climate change effects become more significant, more people will be required to move away from their homes
- Climate change also uniquely harms agricultural productivity
** Summary
- The Green revolution supported exponential increases in global population. Temporal changes in human behavior, production, and pollution are asociated with the Green Revoluution
- There are different ways to approach agricultural production
- Human migration patterns, economic development, and agricultural production are inextricably linked
** Energy, Coal, Oil, and Gas
- Forms of hyrdocarbons
  - Fossil fuels: nonrenewable resources like coal, oil, and natural gas that were formed over millions of years from the remains of dead organisms
  - Forms the majority of the energy used by modern society
  - Crude oil (liquid). natural gas (gas), coal (solid)
** Electricity Generation
- US: 33% coal, 33% natural gases, 19% nuclear, 7% renewable, 6% hydroelectric
  - Drawbacks; greenhouse gases, acid rain, acid mine drainage, particulates
- EROEI of Coal
  - Energy return on energy investment (EROEI): A measure of the net energy from an energy source
  - Energy in the source - Energy required to get, process, ship, and use it
  - EROEI of coal = 11.5:1
** Coal Formation
- Process of coal formation occurs best in river deltas/coastal plains
- Formation of Appalachian Mountains were the last and greatest of the events that joined all of the world's land into one super-continent
- Coal is mined from underground or surface mines (now accounts for 60% of coal produced in the US)
  - Top coal producing states: Wyoming > Kentucky > W Virgina
- Surface mining: Occurs at depts above 180 ft
  - Strip mining
  - Open pit mining
  - Mountaintop removal mining
  - Highwall mining
- Underground mining: Below 300 ft, accounts for 60% of world coal production
** Coal Transportation
- shipped by train or barge to destination
- may be refined before shipping (washing w water or chemical bath to remove impurities)
- when coal arrives at the power plant, it is pulverized into a heavy powder that is suitable for burning
** Advantage of Coal
- Widely distributed around the world
- Proven reserves are est to last for 100 more years
- Easier and sager to transport compared to other fossil fuels
- Affordable
** Disadvantages of Mountaintop Removal
- Higher rates of cancer, respiratory diseases amongst miners and local communities
- Loss of forest and compaction of soil
- Explosions send rock and debris flying
- Toxic substances permeate region's rivers
- Coal extraction creates toxic slurry
- Toxic fly ash created 
* 12.02.20
** Provisioning Services
- Products obtained from ecosystems
- Pharmaceuticals
- Fruits and vegetables
- Fish and game
- Timber, fiber, fuels
** Plants as food
- 400,000 species described
- 14 species provide most of our food
- 3 crops (corn, wheat, rice) account for half of the world's calorie consumption
** The Green Revolution
- Normal Bourlaug - Father of the Green Revolution
  - Selective breeding increased crop yields throughout the world in the 1960s
  - Won many different prizes (National Medal of Science, Congressional Gold Measure, Public Welfare Medal, Nobel Peace Prize, Presidential Medal of Freedom)
- Shortly after the 20's and the rise of higher crop yields, the dust bowl and great depression hurt agriculture significantly
- The 1960s Green Revolution increased food supplies worldwide
** The Basis of the Green Revolution
 - Nitrogen and phsphorus fertilizer, irrigation and pesticide use are unsustainable
- Production increased during the green revolution even though the area under cultivation remained approx. the same
- Production leveld off in the 1980s, only to rise again at the turn of the century, where genetic engineering technologies were used to develop new crop varieties
** Feeding the Global Population
- Global pop expected to reach 10B by 2050
- Experts say we will need to produce twice as much food
- Eventually crop productivity reaches a limit
** Green Revolution Impacts, Limits, Future
- Povery and food insecurity persisted despite advances
- Nutrition: Calorie availability increases but micronutrient intake is lagging
- Environmental impacts have been mixed
  - Positive: Less overall land used
  - Negative: Increased pesticide use
- Gains in Africa lag significanrlt but are catching up
- Green Revolution 2.0
** Importance of Food Self-sufficiency
- Food self-sufficiencyL ability of an individual nation to grow enough food to feed its people
  - Africa largely overlooked by green revolution, lack food self-sufficiency
- Food sovereignty: ability for an individual nation to control its own food system
  - Africa also lacks food sovereignty
** Africa & Hunger
- Industrialization and farm subsidies enabled mostly US farmers to produce vast surpluses of what, corn, and soybeans
- Global market flooded w cheap food
- Smaller countries can't compete
- Much of their farmable land used for cash crops, which are exported
  - Cash crops: Food and fiber crops grown to sell for profit rather than for use by local families, communities
** Industrial Agriculture: Pros and Cons
- Pros
  - Large scale farming
  - Higher yields
  - Growth in nutrient-poor soil
  - Fewer blemishes
  - Less labor intensive
- Cons
  - Dependence on mechanization
  - Monocultures
  - Decrease in biodiversity
  - 40% of all agriculture consumed by pests/disease
** Locust Outbreaks
- One of the world's most devastating pests
- Can swarm to 80M, eat 2+ grams/day
* 11.30.20
** Human Impacts on the Phosphorus Cycle
- inc fetrilizer use increases phosphorus runoff into waterways, increases eutrophication
- all farmers need phosphorus, but 5 countries control ~85% of world's remaining phosphate reserves
- phsophorus critical to fertility, high crop yields, overall necessary to food production
- phosphorus quickly becoming more expensive
** Major Issues Assiciated with Current Phosphorus Usage
- Inefficient global food system
  - 4/5 of phosphorus is lost/wasted in the supply chain from mine to field to fork
- Cheap fertilizer
  - Farmers need access to phosphorus, yet up to 1B farmers lack access to fertilizer markets
- No Monitoring
  - Currently no international or national policies, guidelines, or organizations responsible for ensuring long term availability and accessibility of phosphorus of food production
** Phosphate Prices
- temporary phosphorus price spikes in 2008 affected farmers from Australia to Ethopia, leading to farmer riots and suicides - was a wake up call to the fragility of the world food sitation
** Sustainable Phosphorus Measures
- Much of phosphorus is lost in waste, can be recycled and recouped
- Critical to maintain a more sustainable diet
** Soil & Soil Dynamics
- Critical Concepts:
  - Physical and Chemical Weathering
  - Erosion
  - How long do soils take to form?
  - Soil loss & conversion
** Physical and Chemical Weathering
- Weathering = breakdown of rocks, soil, minerals often done by water or organisms
  - Physical weathering = simply breaking down rocks
  - Chemical weathering - changing the chemical structure of rock, soil, etc
- Makes up ~50% of the soil
- Takes an extremely long time
** Soil Complexity
- Diverse organisms contribute to soil structure
- Soil is often linked between the different spheres of the world and supports biodiversity significantly
- Climate effects soil in different ways
  - Tropical forest: generally infertile due to heavy rainfall and decomposition rates
  - Temperate forest: usually fertile and neutral to slightly aciding
  - Temperate grassland: neutral to slightly basic, high to moderate fertility
  - Desert: low fertility and organic magter, often high in salt content
- It can take 500+ years for 2.5 cm of soil to form
- Poor land use practices cause soil erosion
** Weathering vs Erosion
- Weathering: the breakdown of rock to soil (creating soil)
- Erosion: the movement of soil, minerals, etc to another place (taking away soil)
- Overgrazing: removal of plant matter by livestock exposes soil to erosion
- Deforestation exposes soil to loss
- Desetification: Semiarid range land becomes permanently less productive when overgrazed
** Summary
- There are biotic and abiotic components of ecosystems
- Global biogeochemical cycles are essential to supportiong biology and the economy
- Phosphorus is especially important. It is distributed heterogeneously and limitation of it may compromise agricultural production. An excess of phosphorus is a major quatic pollutant
- Access to elements will govern patterns in economic and technological development
- Soils are complex and take extremely long times to form. Soils are strongly influenced by climate.
- A variety of activities compromise soils.
* 11.23.20
** Tomato Agriculture
- Tomato is one of the most valuable crops in the world
- Originally from S America, transported to Europe by early 17th century, back to N America in 18th century
- Annual production > 175M tons, 85B USD
- Important plant model
  - 15,000+ known varieties
  - Member of important Solanaceae family
** Ecosystems
- The provisioning of ecosystem services is dependent upon functioning ecosystems
- Biosphere: the total area on Earth where living things are found; the sum total of all biomes
- Ecosystem: all of the organisms in a given area + the physical environment in which, and with which, they interact
- Community: all the populations (plants, animals, other species) living and interacting in an area
- Population: all the individuals of a species that live in the same geographic area and are able to interact and interbreed
- Ecosystem ecologists: study how ecosystems work in relation to their biotic and abiotic components
- Population ecologists: study how populations change over time and space
- Community ecologists: investigate the factors that influence biodiversity, community structure, and the distribution and abundance of specie
** Energy and Matter
- All ecosystems function through:
  - Matter cycles: movement of life's essential chemicals/nutrients through an ecosystem
  - Energy flow: the one-way passage of energy through an ecosystem
- Earth is materially closed but energetically open
- Biomass can't enter or leave the system, but energy can
- Energy enters as sunlight through either heat or light
- Photosynthesis: the chem eraction done by producers to convert energy of the sun using carbon dioxide and water -> sugar and oxygen
** Biomes
- Biomes: specific portions of the biosphere determined by climate and identified by the predominant vegetation and organisms adapted to live there
- Biomes are divided into three main categories
  - Terrestrial
  - Marine
  - Freshwater
** Limiting Factors & Distribution
- Limiting factor: the critical resource whose supply determines the population size of a given species in a given ecosystem
- Range of tolerance: the rande, within upper and lower limits, of a limiting factor that can limit population size
- Limiting factors determine the distribution and size of populations
- Variability increases a population's range of toleration, expanding its distributoin and increasbing the chance that it will be able to adapt to changing conditions
** Review
- Food insecurity is global and heterogeneous
- There are 4 types of ecosystem services
- Biophysical charactersistics of systems govern what and how much of a crop can be produced into a region
** Matter
- Matter cycles that move nutrients through ecosystems depend on living organisms and abiotic sinks of those resources
- Biotic: the living, organic components of an ecosystem
- Abiotic: the non-living compoenents of an ecosystem, important for nutrient cycling
- BiogeochemistryL the ways in which an element or compound moves between its various living and nonliving forms and locations in the bioshphere
- Elements required for life: Carbon, Hydrogen, Ditrogen, Oxygen, Phosphorus, Sulfur
- Biogeochemical Cycles:
  - Water cycle
  - Carbon cycle
  - Nitrogen cycle
  - Phosphorus Cycle
** Carbon Cycle
- Photosynthesis: Plants and other photosynthetic organisms produce sugars
  - Utilize sunlight and CO2, produce oxygen
  - Photosynthesizers known as producers
- Cellular respiration: Organisms break down sugar to release energy
  - Utilizes oxygen, produces CO2, known as consumers
** Nitrogen Cycle
- Nitrogen is the most abundant gas in the air but has a very tight bond, bond must be broken (fixed) before use by producers
- Nitrogen cal also be released back into the atmosphere
- Nitrogen Cycle: a continuous series of natural processes by which nitrogen passes from air -> soil -> organisms -> air/soil
- Nitrogen enters ecosystem through nitrogen fixation
- Nitrogen exits the ecosystem when other bacteria convert nitrate back to molecular Nitrogen
- Humans are disrupting the nitrogen cycle
  - Fertilizers and emissions are doubling availbility of nitrogen
  - While nitrogen is no longer a limitng factor for plant growth, the additional notrigen can disrupt the ecosystem
** Phosphorus Cycle
- Different than other cycles because phosporus doesn't exist in the atmosphere
- Only found in solid, liquid form
- Phosphorus cycle: a series of natural processes by which phosphorus moves from rock -> soil, water -> living organisms -> soil
* 11.20.20
** What does it take to grow a tomato?
- Nursery (Water, energu, materials, presicides, etc)
- Nursery to farm transport
- Cultivation (Pesticides, land use, tillage, etc)
- Farm to Packaging-House transport
- Packaging (Energy, water, packaging)
- Transportation (Freight ship route, truck route)
** Ecosystem Services
- Provisioning Services (Prodicts obtained from the ecosystem)
- Regulating Services (Benefits from regulation of ecosystems)
- Cultural Services (non-material benefits obtained from ecosystems)
- Life on earth depends on ecosystem services provided by natures
- Recognizing the value of rhese services may motivate us to protect them
** Nutrition
- Currently produce 1/3 more calories than needed
- UN 2013, 842M people (12% of the world) suffers from undernutrition (not enough calories)
- Civil war and Climate change contribute to a significant increase in recent famine
- Although we produce enough food to feed everyone, nearly 1B people don't have access to enough nutritious food
- The rise of industrial agriculture and the Green Revolution helped fight hunger in the 20th century but came w some unintended consequences
- Employing a variety of agricultural methods and addressing socioeconomic drivers of poverty necessary to fight hunger
** Food Security
- Food security: having enough physical, social, and economic access to sufficient safe and nutritious food
- Food insecurity is a problem due to
  - Inadequate distribution of food
  - Inadequate funds to buy food
- Undernourishment: When a person does not have enough to eat
- Worldwide, 1/4 children experiences stunted growth due to undernutrition
- Malnutrition: a state of poor health that results from a nutritional imbalance due to a lack of essential nutrients
  - can serve as a prelude to many duseases
  - UN est that the cost of treating malnourishment in children under 2 is double of the cost to prevent it in the first place
- Overnutrition: the consumption of too many calories
  - considered a form of malnutrition
  - affects 1.5B people
  - increases susceptibility to diseases
  - problem of both the wealthy and poor
- Protein deficiency -> Kwashiorkor
- Calorie and protein deficiency -> wasting disease
- Vitamin deficiency -> many diseases
** Food Deserts
   - 13/30 of athens census tracts are labeled as food deserts, 33% of residents live 1+ mile from a grocery store
* 11.11.20
** Cannabis & Sustaibaility
- Now that cannabis legalization is sweeping North America, we need to better understand its impact on freshwater systems
- 2/3 of Americans believe that marijuana should be legalized
** Cannabis & The Economy
- Cannabis may be key to economic recovery, potentially post COVID, similar to how ending prohibition helped end the Great Depression
- 10s to 100s of Millions made off of Marijauna tax revenue
- California is the biggest producer with nevada as the runner up for marijuana
** Cannabis & Society
- Many states are no decriminalizing Marijuana and allow for medical Marijuana use
- Without legalization, marijuana feeds non-violent offenders into the prison system, perpetuates mass incarceration, and disproportionately affects POC
- California was the first state to allow medical use of Marijuana, many states have created laws since then
** Cannabis and the Environment
- California case study, Pot takes up very significant amounts of water, no regulation
- Groundwater use has triggered conflicts across areas of California
- Water rights are a large concern in the Marijuana industry, especially for California because unlicenced growers often steal other's water
- US DEA est. that 60% of cannabis consumed nationwide is grown in California
- Bulk of that comes from three upstate counties of the Emerald Triangle: Mendocino, Humboldt and Trinity.
- This is because the conditions there are perfect for Cannabis growth but this comes with problems for the environment, waterways, and wildlife
- Creek Diversions threaten fish habitats
- Road building erodes soil, streams
- 1 marijuana plant growing in a national forest uses 900 gallons of water per growing season
- In 2017, 1.25 Million plants were found growing in CA national parks
- Illegal marijuana growth therefore uses 1.1 Billion gallons of water
** Tristate Water Wars
- For 30 years, GA, AL, FL have fought over the sue of water in the Apalachicola-Chattahoochee- Flint River Basin (ACF) which is heavily infleunced by the US Army Corps of Engineers' operation of Lake Lanier's Buford Dam. Lanier lies within Chattahoochee's headwaters, north of Atlanta
- 70: the number of attorneys on retainer by GA
- 4 Million: Pages of documents produced by GA agencies, universities and non-profits requested by FL.
- 660,000 emails give to GA by FL
- 45 people deposed by both GA and FL
* 11.02.20
** Triple Bottom Line
- An assessment of the cost of a good or service should include more than just the economic costs; it should also include the social and environmental cost
- IPAT Equation:
  I = P * A * T; I = Impact, P = Population size, A = Affluence(products/person), T = Tech Usage (impact/product)
** Assumptions of Mainstream Economics
- Environmental economists argue that mainstream economics will fail in the long run because it makes some assumptions that are inconsistent with the way nature operates
**** Assumption:
- Natural and human resources are infinite, substitutes can be found as necessary
- Economic growth will go on forever
- Something that benefits/harms us today is more important than something that ight do so tomorrow
**** Impacts:
- Linear economic production models use inputs and produce waste without regard to sustainability; circular systems depend on renewable resources and see waste as a useful inp
- Cradle to Cradle mentality creates sustainability whereas crade to grave increase the amount of overall waste
** Market solutions
- Alternatve: Command and Control
  - Command = estbalishment of performance standards by a govt authority that must be complied with
  - Control = negative consequences that could result from non-compliance
- Performance Standards
- Tradeable permits
  - Important to consider the effect on environmental justice
Economic Incentives
  - Seek to reduce or eliminate negative environmental externalities (such as pollution) by incorporating the external cost of production.
  - The general focus is prevention rather than remediation
- Payment for Ecosystem Services
  - NYC protecting its water supply
** Environmental Policy
- Environmental policy = A course of action adopted by a government or organization intended to improve the natural environment and public health and reduce human impact on the environment
- Collective action undertaken to manage natural resources and human impacts on the environment.
- Things like:
  – Laws
  – Regulations
  – International agreements
  – Funding decisions
** Why is Environmental Policy Challenging
- Many environmental problems trasncend boundaries
- Lots of WICKED problems, very complex with mulitple stakeholders
- Lawmakers must juggle many factors
  - Effectiveness of the policy
  - Negative tradeoffs
  - Cost burden (internal, external costs)
  - Flexibility of the policy to accomodate changes
- Many times, voters and lawmakers don't agree that they are necessary
** History of Environmental Policy
 - Before 1960's
   - How best to use resources
   - Pollution not key objective
   - Primerily dealt with at the state level
   - Environmental problems addressed after the fact through litigation, favored the pollutor
 - Changes
   - As industry, pollution inc, pollution crossed state lines
   - Massive outcry in the 60's and 70's lef to federal legislation
   - Performance standards let to a prevention-focused regulation
** Who Makes Environmentla Policy?
- Elected Officials
- Federal and State Agencies
- Local departments: planning and zoning, public works, etc/
- Courts
- Corporations and other businesses
** NEPA
- NEPA’s key feature is the Environmental Impact Statement (EIS)—a report that details the likely impacts (positive and negative) of a proposed action.
- The goal of an EIS is to identify problems before they occur so that stakeholders can choose the most acceptable course of action.
- The findings are made available to everyone (citizens, policy makers, and special interest groups)—this keeps the process transparent and everyone is given a chance to respon
** Policy Decision Making Process
- Identify problem -> Consider options -> Formulate Plan -> Adopt Law -> Implement Law
  -> Evaluate effectiveness
- Statutes:
  - Provide policies, goals
  - Typically mandate an agency to promulgate regulations according to staturoy standards and enforce them
  - Often authorize states to enforce them
  - Often dictate funding allocations
- Regulations:
  - Regulation = rule = administrative law
  - The actual technical and programmatic standards for environmental protection
  - Standards usually in regulagtions instead of statutes because of ease of amendment
- Court Decisions
  - Rule on constitutionality of statute, regulation, or other deferal action
  - Rule on application of statue or regulation
  - Rule on meaning (language/intent)
- Executive Orders
  - Presidential directives to do something
  - Often involve internal affairs, Development of amendments to regulations
** Misc
- Most environmental regulation passed between the 70's and 90's, no significant regulation since
- Enforcement and Definitions absolutely essential
- Trump and Environmental Policy
  - Treaties
  – Paris Climate Agreement
  - Agency heads, federal judges
  - Agency directives –rules/regulations
  - Rule rollbacks
  - No new rules or policies
  - More state authority
* 10.26.20
- Disease cases frim infected mosquitoes, ticks, and fleas have tripled in the last 13 years
** Malaria
- Vector: Mosquito
- Transmission: Bite from infected mosquitoes
- Prevalence: Est 219M cases of Malaria, cases are mostly children w 660k Deaths
- US Prevalence: An average of 1,500 reported cases of malaria in the U.S. each year
** Dengue Gever:
- Vector: Asian tiger mosquito (in 36 US states)
- Transmission: Bite from infected mosquito
- Prevalence: 100M cases worldwide, endemic in the Americas
- Occurs rarely, but there is a small risk for dengue outbreaks in the continental United States, mainly in the Southern US
** Chikungunya
- Transmitted by mosquitoes
- Mainly in Africa, Asia, Europe, Indian, and Pacific Oceans
- First found in the Americas on Carribean islands in 2013
- Beginning in 2014, reported in US travelers
** West Nile Virus
- Vector: Mosquito
- Transmission: Bite form infected mosquito
- Prevalence: commonly found in Africa, Europe,Middle East, North America, West Asia
- U.S. Prevalence: Between 1999 and 2012, about 37,000 cases of West Nile Virus were reported in the U.S. Over 1,500 people died as a result.
** Spread of Disease
- Increased connectivity increases rate and spread of infectious diseases across the globe
- Correlation between travel advisory and amount of travel to infected areas for Zika
- Zika most likely to be found in the Southeast because of Zika-transmitting mosquito population residence
- High poverty rates correlated with high risk of disease spread due to high population density, potential lack of good healthcare
- Warmer average temps, longer growing seasons, changes in precipiation may lead to more standing water and conditions that may be better for disease spread
- Warning temps could expose more than 1.3B people to Zika by 2050
** Climate Change and Health
- Without effective responses, climate change will:
  - Water quality and quantity:  Contributing to a doubling of people living in water-stressed basins by 2050.
  - Food security: In some African countries, yields from rain-fed agriculture may halve by 2020.
  - Control of infectious disease: Increasing population at risk of malaria in Africa by 170 million by 2030, and at risk of dengue by 2 billion by 2080s.
  - Protection from disasters: Increasing exposure to coastal flooding by a factor of 10, and land area in extreme drought by a factor of 10-30
- Rainfall: tranports and disseminates infectious agents
- Flooding: sewage treatment plants overflow, water sources contaminated
- Sea levels rise: Increased risk of severe flooding
- Higher temps: increases growth and survival rates of infection
- Drought: increases concentration of pathogens, hurts hygiene
** Health Outcomes from Climate Change
- Some expected impacts will be beneficial but most will be adverse.Expectations are mainly for changes in frequency or severity of familiar health risks
- See Zika Climate Final for diagrams
** Poverty and Disease
- Diarrhea is related to temperature and precipiatation; Diarrhea increased 8% for each 1 degree C temp increase
- Health impacts of climate change unfairly distributed, hurt mortality of developing, low-income countries, especially in Africa
** Temperature Effects on Vectors and Pathogens
- Vector:
  - Survival inc/dec depending on species
  - Changes susceptibility of vectors to some pathogens
  - Changes in rate of vector population growth
  - Changes in feeding rate and host contact
- Pathogen:
  - Decreased incubation period at higher temps
  - Changes in transmission season
  - Changes in georgraphical distribution
  - Decreased viral replication
** Percipitation Effects on Vectors
- Survival: increased rain may increase larval habitat
- Excess rain can eliminate habitat by flooding•Low rainfall can create habitat as rivers dry into pools (dry season malaria)
- Decreased rain can increase container-breeding mosquitoes by forcing increased water storage
- Heavy rainfall events can synchronize vector host-seeking and virus transmission
- Increased humidity increases vector survival and vice-versa
** IPCC
- Intergovernmental Panel on Climate Change, intl body for assessing the science related to climate change
- Set up in 1988 by the World Meteorological Organization and the UN Environmental Programme
- Provide policymakers w regular assessments about climate change, impacts and future risks, options for mitigation and adaptation
* 10.14.20
- Exam Review
  - Taxonomoc group with the most known species: insects
  - Types of biodiversity
    - Genetic
    - Species
    - Ecosystem
  - Biodiversity in the Southeast
    - Describe SE biodoviersity using the terms "richness," "endemic," and "hotspot"
  - Mussels: diversity, life history, and ecosystem service (nutrient cycling)
  - What is diversity?
- Isolation & Extinction Risk
  - Hawaii's biodiversity is vulnerable to extinction - more than 90% of native species on Hawaiian islands are endemic, one half of indigenous species face extinction
** Community Ecology
- Mutualism - A symbiotic relationship between individuals where both species benefit
- Parasitism - A symbiotic relationship between individuals of two species in which one benefits and the other is negatively affected (may or may not lead to death)
- Commensalism - A symbiotic relationship between individuals of two species in which one is benefitted and the other is unaffected
- All species contribute to theur ecosystem but some are more important than others
- Keystone species influence community structure disporportionately to their abundance
  - Role: create/modify habitats, influence interactions between other species
  - Removal of a keystone species may lead to a loss of biodiversity and changes in community structure within the ecosystem
- Food web: complex and realistic representation of how species feed on each other in a community
- Food chains: a linear representation of how different species in a community feed on each other
- Producers and Consumers
  - Producers: photosynthetic organisms that capture energy directly form the sun and convert it into food
  - Consumers: organisms that gain energy and nutruents by eating other organisms
    - Animals, fungi, most bacteria, and protozoa
- Trophic level - a level in a food chain or food web
  - Primary consumer: a species that eats producers
  - Secondary consumer: a species that eats primary consumers
  - Tertiary consumer: a species that eats secondary consumers
  - Decomposers can be put practically anywhere on the food web
- Conservation Status: IUCN Designations
  - The International Union for Conservation of Nature established the Red List of Threatened Species in 1963
- Single species conservation programs focus on an individual species, successfully protecting some high-profile species but are less often used for less visible or valued species
- CITES
  - Convention on International Trade in Endangered Species of Wild Flora and Fauna
- Lacey Act: First law protecting wildlife
* 10.12.20
** Definitions of Diversity
- Genetic Diversity: Variations in the genes among individuals of the same species
- Species Diversity: The variety of species present in an area; includes the number of different species that are present as well as their relative abundance
- Ecological Diversity: The variety of habitats, niches, trophic levels, and community interactions
** Robust Redhorse
- Thought to be extinct until rediscovered in the Oconee in 1991
- Extripated: Extinct in a local area
** Species Diversity
- Richness: number of different species
- Evenness: relative abundance of each species
- Diversity: combined richness and evenness
** Endemic Species
- Because areas w high ecological diversity offer many habitats and niches, they have a large number of endemic species
- Endemic species: a species that is native to a particular area and not usually found elsewhere
  - Most commonly found in small ecosystems
** Hotspots
- Biodiversity hotspots: areas that have high endemism and have lost at least 70% of their original habitat
- These areas contain a large number of endangered species (species at high risk of becoming extinct)
- The Southeast US is a global hotspot of freshwater biodiversity supporting 2/3 of the country's fish species, over 90% of the US total species of mussels and nearly half of the global total of crayfish species
** Habitat v Niche
- Habitat: the physical location of an species
- Niche: the biotic and abiotic needs for a species to survive
** Biodiversity Loss
- As much as 20% of the world's biodiversity may be lost in the next 30 years
- 50-66% of biodiversity may be lost by the end of the century
- Current rate of extinction is 1500 times greater than pre-human background rate
** Causes of Biodiversity Loss
- Human actions are having significant impacts on biodiversity loss
- Threats include:
  - Habitat destruction
  - Invasive Species introduction
  - Pollution
  - Overharvesting
  - Climate change
** Value of Biodiversity
- Provides key connections between species and their environment
- Provides direct protection against disease
- Provide food, fuel, building materials, and pharmaceuticals
** Ecosystem Services
- Supportive Services:
  - Purification of air and water
  - Carbon sequestration
  - Erosion Prevention
  - Habitats for animals and Plants
- Provisioning Services: Food, resources, water, fuel
- Regulating Services: Pollination, seed dispersal, protection, biological control
- Cultural Services: Recreation, Spiritual Tourism, mental health
- Human Wellbeing:
  - Strong economic growth
  - Medicinal resources
  - Reduction in toxin exposure
** Isolation and Extinction Risk
- Number of unique species increases with isolation
  - Isolation and high endemism makes remote islands particularly vulnerable to species loss
  - Human impact contributes to isolation in the form of habitat fragmentation
  - Habitat fragmentation: destruction of part of an area that creates a patchwork of suitable and unsuitable havitat areas that may exclude some species altogether
* 10.09.20
** Evolution and Resistance
- Evolution happens to populations, not individuals
- Natural selection is the mechanism for evolution
- Genetic drift more likely with low population size
- The potential for antibiotic resistance to develop in bacteria is very high
- Improper waste disposal
** Athens Water Quality
- 10/17 Athens watershed are impaired or unhealthy
- Athens drinking water comes from:
  - N Oconee River
  - Middle Oconee River
  - Cedar Creek
- Athens had E. Coli outbreaks in water, showing prevalence of bacteria
** Gonnorhea & Resistance
- Gonorrhea treatment is done through antibiotics
- Shown increase in resistance to every drug used to treat Gonnorhea
- CDC currently recommending two-drug comination to preserve our last
  highly effective antibiotic
- Higher reported rates of Gonnorhea occur in SE US, on an overall upward
  trend with younger populations
** Developing new Antibiotics
- First antibiotic developed by Alexander Fleming in 1982 after noticing the fungus penicillium could kill disease causing bacteria
- Antibiotics aren't profitable for drug companies
- Developing antibiotics are high risk, very expensive, and very difficult
- Low return on investment, development void since 1990
** Post-antibiotic Era
- Currently:
  - 80% of gonnorhea infections now resistant to antibiotics- 440,000 new cases of resistant tuberculosis annually
- In the future
  - Strep throats to scraped knees could be deadly
  - Cost to treat drug resistant double that of the status quo
- Davos Declaration
  - Reducing the development of drug resistance.
  - Increasing investment in R&D that meets global public health needs.
  - Improve access to high-quality antibiotics for all.
  - Signed by 98 companies, 11 industrial associations in 21 countries
* 10.07.20
** Genetic Diversity & Natural Selection
- Genetic diversity in a population is the raw material natural selection
- The larger the amount of genetic diversity, the higher probability that some individuals from
  that pool can survive changes to its environment
- Phenotype = expressed gene
- Natural selection acts directly on the phenotype, resulting in changes in allele frequencies
  from parental to offspring generations
* 10.05.20
- Following widespread usage of antibiotics on humans and animals, waste from livestock and humans
  is generating antibiotic-resistance bacteria
- These bacteria are getting back into the environment through out waste
** Antibiotic Resistance:
- A complex problem that involves helping many actors see the big picture and not just their
  part of it
- Issues where an action affects (or is affected by) the environment surrounding the issue,
  either the natural environment or the competitive environment
- Problem whose solutions are not Obvious
** Systems Thinking
- Considers the whole rather than parts of the whole:
  - Events
  - Patterns 
  - Underlying Structure
** Cycle of Infection
- Farm animals recieve antibiotics often, developing resistant bacteria in their gut
- This can be transmitted through produce, waste, shared environments, etc.
** Bacteria
- Bacteria are single celled organisms that can grow in colonies
- Many different kinds of bacteria can grow together in similar environments
** Explaining Resistance
- Antibiotics kill almost all antibiotic sensitive bacteria, leaving few sensitive and many unsensitive
- Reproduction occurs with the mostly-unsensitive remaining bacteria, leaving to many unsensitive off-
  spring. This increases the amonut of resistant bacteria as a whole.
** Genetic Variation
- Variation in the susceptability of bacteria to antibiotics allows for the propogation of 
  these genes in bacterial communities
- Individuals of the same species have the same basic gene
- Alleles: variants of genes that account for the diversity of traits seen in a populat
- Adaptation: traits that promote the success of a species
- An adaptive trait for one environmental condition does not mean that it is adaptive for all conditions
** Genetic Diversity
- Within populations, biodiversity is measured by genetic diversity
- Genetic diversity improves survival of a population
- Outbreeding, through sexual reproduction of not closely related individuals, maximizes genetic 
  diversity
- Inbreeding, or mating between closely related individuals, results from small 
  populations, and increases chances of genetic diseases (e.g., hemophilia, cystic fibrosis, etc.)
** Sources of Genetic Variation
- Mutation: A change in the DNA sequence of sex cells that alter a gene
  - Can be neutral, beneficial, or harmful
- Genetic Recombination: The production of eggs and sperm that results in a shuffling of 
  alleles, creating new combinations in offspring
** Natural Selection
- Constant struggle of organisms to survive and mate
- Organisms tend to produce more offspring that can survive
- Individuals of the same species are not identical
- Evidence of Natural Selection: Selective breeding (artificial selection) of dogs and cats
- Natural selection results in changes in gene frequencies
  - Some individuals will be able to obtain more resources and can produce more offspring
   - Differential reproductive success results in changes to gene frequencies
* 09.18.20
** Hurricanes
*** How Hurricanes Form
  - Water evaporates over the ocean and forms clouds when it touches cold air
  - A column of low pressure develops at the center with winds around the column
  - Speed of the wind around it increases
- Categorized based on wind speed (1-5)
- Hurrican development requires warm water and low wind shear
  - Carribean has warm water all year but also high wind shear which isn't conducive to hurricanes
*** Climate Change & Hurricanes
- Storm surge more dangerous (accoutns for 90% of hurricane deaths)
- 40% increase with a 0.5 decree C inc in temperature
- Increasing of North Atlantic hurricane season
- Climate change is expected to shift the Bermuda high westward
  - Bermuda High is a pressure system over the Atlantic
  - Has the ability to move hurricanes on the Atlantic
*** Hurricane Harvey Intensification
  - Went from a tropical depression to a Cat 4 Hurricane in 57 hours
  - Soil in TX affected the amount of water maintained in the Earth
  - Huge economic impacts
*** General Impacts
  - Storm Surge
  - Extreme Rainfall
  - Potential Wind Speed
* 09.16.20
** Heat Waves
- Heat extremes doubled in frequency from 1980-1999 to 2000-2019
- Climate change affecting heat waves
  - Shifting the frequency of hot and cold weather, heat waves are more frequent
  - Exacerbating heat inducing droughts, dry land leads to even hotter temps
- Causes: Global warming ->
  - Large scale global circulation change
  - Atmospheric Blocking increase
  - Air mass temp increase
- Effects and Consequences
  - Decreased human productivity
  - Increased tropical disease and death
  - Environmental racism
  - Crop productivity decreases
  - Lower biodiversity
  - Decreased water availability
  - Increased fire risk
** Wildfires
- Climate change is increasing the size, intensity, and frequency of wildfires
- Wildfires create more cimate change through the increase of carbon expulsion through wildfires
- Wildfires have global impacts due to smoke and temperature changes
- Wildfire season has gotten longer due to climate change 
* 09.14.20
** Coriolis Effect
- Deflection of an object's path due to the rotation of the Earth
- North and south poles have different deflections of wind patterns
- Little/no deflection at the equator
** Air circulation
- Hottest air at the equator, moves north or south, cools, then comes back into equator
*** Cells
- Hadley cells: 0-30 degrees North and South
- Ferrell Cell: 30-60 degrees North
- Polar cells: North and South poles
- Northeast and Southeast trade winds (remember directions!)
- Westerlies: bring rain and precipitation
** Surface Ocean Currents
- Ocean currents also affect the distribution of climates
- Surface ocean currents generated by wind, Coriolis effect, heat, and continents
- Heat redistribution from the Tropics
  - Trade winds push warm surface waters west
  - Water reaches continents and flows north and south
  - water cools
  - Westerlies push cooler water east
  - Water reaches continents and flows to equator
** El Nino (Southern Oscillation)
- Recurring climate pattern involving changes in the termperature of waters in the central
    and eastern tropical Pacific Ocean.
- The ocean and atmosphere can interact to affect climate
  - Water in the eastern pacific warms up
  - Sea level pressure drops but rises in the W pacific
  - Trade winds weaken
  - Upwelling in the Pacific is reduced
  - Warmer waters - increased rainfall in Peru
  - Cooler waters, drought in Australia/Indonesia
- Critical because of its ability to change atmospheric circulation, temps, and percipitation
- Significantly hurts fisheries and developing countries
** La Nina
- exacerbates normal conditions and leads to cooling in the Eastern pacific
** Heat Waves 
- Global warming has amplified the intensity, duration, and frequency of 
  extreme heat and heat waves. 
* 09.11.20
- Northern latitudes experience greater seasonality in CO2 concentrations
  - This is due to variation in photosynthetic activity by plants
- Greenhouse effect
  - Some incoming solar radiation is absorbed
  - Other amounts are reflected back into the atmosphere
  - Greenhouse gases capture and reradiate some heat over and over, warming the Earth
  - More gases, more heat
- Albedo: measure of the reflectivity of a surface
  - light surfaces have a higher albedo, darker surfaces have a lower albedo
  - surfaces with a low albedo release more heat into the atmosphere
- Positive Feedback Loops
  - applied to albedo:
  - temps rise -> more ice melting -> more water warming -> temps rise
- Urban Heat Island Effect
  - cities will be inc their population, inc energy and temperature
  - cities in particular have higher temperatures
  - tree cover -> cooler temperatures
- Small changes in overall global temp can cause significant changes
  in weather creating more extreme storms and more record temps
  - roughly twice as many heat records
  - alterations in global jet streams
  - frost comes later and begins earlier
- General climate change impacts:
  - Health impacts
  - Crop productivity
  - Coastal erosion
  - Biodiversity
  - Water availability
  - Fire risk
- Weather events getting more extreme with
  - sea levels
  - wildfires
- Need both adaptation and mitigation
  - Adaptation: Responding to warming that has already happened
  - Mitigation: Preventing further warming by addressing climate change causes
* 09.09.20
** The Earth's Atmoshphere
- Climate change is a serious environmental problem impacting species, ecosystems, and the globe
- The atmosphere helps protect the Earth from the sun and keeps the temperature of the Earth cool
- Atmosphere has a significant impact on climate
- Earth's Atmosphere Composition
  - Nitrogen (78%)
  - Oxygen (21%)
  - Other - Greenhouse Gases (1%)
** The Keeling Curve
- Curve developed to track atmospheric CO2 levels in Earth's atmosphere since 1952
* 09.02.20
** Demographic Transition Model
- Demographers use age structure diagrams to predict future growth potential of a population
  - Pyramid structures indicate fast growth
  - House-shaped structures have moderate growth
  - Diamond structures have low/negative growth
- Development leads to smaller families
- Demographic transitions happen country by country
- Industrialization might not lead to a demographic transition in all countries
  - May not be linked to quality of life
  - Religion/Cultural beliefs
  - Social justice issue, improving the well-being of women and children key to dec. fertility
** Social Justice: Education for Women
- Education of girls & economic opportunities for women are correlated with lower birth rates
- Education empowers women to take control over thri own fertility through: 
  - Birth control
  - Marrying later
  - Delaying childbirth for career opportunities
- Women earning more money is correlated to lower child mortality
** Environmental Impact
- Slowing population growth is critical to sustainability and reducing our population impact
- Our impact on the population is a result of (1) our population size and
 (2) our consumption habits - both must be addressed
- Ecological footprint: the land area needed to provide the resources for, and assimilate
  the waste of, a person or population
** Sustainability
- A dynamic process between the economy, society, and environment
- Sustainable: The process or the activity can be mantained without exhaustion or collapse
  - Intra & Inter-generational issue
  - Capacity of a system to accomodate changes:
    - rates of renewable resource use should not exceed regeneration rate
    - rates of non-renewable resource use should not exceed rate of renewable substitute dev
    - rates of pollution should not exceed ssimilative capacity of the environment
- Sustainable development has three factors:
  - Social equity
  - Economic efficiency
  - Environmental responsibility
** Worldviews
- Culture influences our beliefs through:
  - Knowledge
  - Beliefs
  - Values
  - Learned ways of life
- Worldviews are affected by: 
  - Environmental Ethics
* 08.31.20
** Human Populations
- 3 major sparks of growth
  - Agricultural Revolution
  - Industrual Revolution
  - Green Revolution
- With more food and technology, the population and need for more human labor increased
- The human population is rapidly increasing and the impact of humans is due to:
  - More humans overall
  - Greater growth / person
- To address population growth, we need to pursue a variety of approaches that address factors
  encouraging high birth rates
- Zero population growth: the absence of population growth, occurs when birth rates = death rates
  - Replacement fertility is reached
** Population Ecology
- Analyze and categorize human populations using population ecology techniques
- Population Ecology: a branch of biology dealing with the number of individuals
  in a particular species in an area over time
- Ecologists study populations to understand what makes them survive and thrive
- Size, distribution, and growth rate is influenced by a variaty of factors and are important to 
  understanding popilation ecology
** Monitoring Population Dynamics
- Population Dynamics: Changes over time in population size and composition
- Important metrics:
  - Minimum viable population - min number of individuals that would still allow population to persist or grow
  - Carrying Capacity (K) - the maximum population size that a particular environment can support indefinitely
- Population Density - the overall desnity a particular populaiton can sustain
** Exponential Growth & Populations
- Exponential growth occurs in populations when growth is unrestricted. This is, overall, unsustainable
- Growth which becomes progressively larger each breeding cycle
- Produces a J curve when plotted
** Monitoring Population Growth
- Population growth rate - the rate at which a population of a species grows over time
- Growth factors - factos which assist in the growth of a population
- Resistance factors - factors which inhibit the growth of a population
- Limiting factos: resources needed for survival but that may be in short supply
** Logistic Growth
- Occurs when a population nears carrying capacity (k) 
  - Maximum sustainable population size
  - Determined by limiting factors
** Density-dependent/ Density-independent Factors
- Density dependent factors increase as populations grow, typically biotic
  - Disease
  - Competition
  - Predation
- Density independent facts affect population growth regardless of population size
  - Storm
  - Fire/Flood
  - Avalanche
** Regulation
- Tendency for populations to decrease in size when above acertain level, and increase
  in size below that level
- Populations can only be regulated by density-dependent factors
- Top down Regulation
  - Predation
  - Disease
- Bottom up Regulation
  - Nutrients
  - Water
  - Sunlight
* 08.28.20
** What is Science?
- Science: a body of knowledge that allows us to understand the world around us
- Science is based on empirical evidence
- Science allows us to test our ideas and evaluate the evidence
- Scientific knowledge, including facts, theories, and laws, is subject to change
- Scientific claims change as new evidence is made available
** White-Nose Syndrome Case Study
*** About WNS
- White-Nose Syndrome
  - 2007-2016, 6+ million bats dead as a result of White Nose Syndrome
  - The reason for the deaths was White-Nose Syndrome
- Chytridiomycosis
  - Infectious, fungal disease affecting amphibians
  - Helped understand white-nose syndrome with bats
*** Science with WNS
- Scientific Method: the procedure used to empirically test a hypothesis
  1. Observations generate questions
  2. Choose a question to investigate
  3. Consult literature
  4. Develop a hypothesis and make a testable prediction
  5. Design and carry out a study
  6. Analyze data
  7. Draw a conclusion
- Inferences: Conclusions drawn based on observations
- Hypothesis: An inference that proposes possible explanation that includes previous knowledge/observation
- Testing a Hypothesis: Hypotheses can be tested through an observational or experimental study
- Scientific Studies: A fair test with results that could support or falsify the research prediction
  - Experimental Studies: Conditions are manipulated intentionally
    - Test Group: the group in an experimental study such that it differs from the control in only one way
    - Control Group: the group in an experimental study to which the test group's results are compared 
  - Observational Studies: Gather real-world data without any intentional variable manipulation
- Theory: A hypothesis that survives repeated testing by significant research can become a theory
- Correlation v Causation
  - Correlation: two things occuring together but not necessarily having a cause-effect relationship
  - Cause-Effect Relationship: the associationof a two variables that identifies one variable occurring
    as a result of the other
  - Observational studies can derive correlation but not causation
  - Experimental studies can derive causational relationships
- Policy: a formalized plan that addresses a desired outcome or goal
  - policies need to be flexible, adapt to new findings, address the environmental problem, fit social need
    and be economically viable in order to work effectively.
** Summary
- Scientific knowledge, through reliable and durable, is never absolute pr certain
- This knowledge, including facts, theories, and laws, is subject to change
- Physical evidence, systematically collected and logically analyzed, helps scientists
  understand environmental issues and guide policy decisions
* 08.25.20
** Applied v Empirical Science
- Applied Science = research whose findings are used to solve practical problems
- Empirical science: A scientific approach that investigates the natural world through case studies
** Social Traps
- Occurs when a large amount of people are using a shared resource
- Seem good in the short term but are actually bad in the long term
- 3 Types:
  - Tragedy of the Commons: When resources are shared, individuals try to maximize personal
    benefit which hurts the resource itself
  - Time delay: Collective decisions that are good today but gone tomorrow
  - Sliding reinforcer: related to the evolution of natural organisms and GMOs
** Beginning with Data Interpretation 
- Variables represent factors that can be manipulated, controlled, or merely measured for research
- Variation = how much a variable changes
- Independent var is controlled to see effects in the Dependent var
- Graphs explore relationships with data and report this data
** Observational v Experimental Studies
- Observational studies can observe a correlation but are unable to derive a causational reln.
- Experimental studies have a control var (required) and are able to derive causactional rlns.
* 08.24.20
** Definitions
- Ecology: the branch of science dealing with the relationships of living things to one another & the environment
- Environmental Science: The study of all aspects of the environment, including physical, chemical, and biological factos, particularly with respect to how these aspects affect humans, and vice versa
- Environmental Ethics: Personal philosophy that influences how a person interacts with their natural environment and thus influences how one responds to environmental problems
** Ecology != Environmentalism
- Distinguish between envrironmentalism & ecology

| Environmentalism                    | Ecology                                          |
|-------------------------------------+--------------------------------------------------|
| Activism to protect the environment | Scientific study of living and non-living things |
