* 09.14.20
- Coriolis Effect
  - North and south poles have different deflections of wind patterns
  - Little/no deflection at the equator
- Air circulation
  - Hadley cells: 0-30 degrees North and South
  - Ferrell Cell: 30-60 degrees North
  - Northeast and Southeast trade wind (remember directions!)
  - Westerlies
  - Polar winds
- Ocean currents also affect the distribution of climates
- Surface ocean currents generated by wind, Coriolis effect, heat, and continents
  - Trade winds push warm surface waters west
  - Water reaches continents and flows north and south
  - water cools
  - Westerlies push cooler water east
  - Water reaches continents and flows to equator
- El nino (Souther Oscillation)
  - recurring climate pattern involving changes in the termperature of waters in the central
    and eastern tropical Pacific Ocean.
  - The ocean and atmosphere can interact to affect climate
    - Water in the eastern pacific warms up
    - sea level pressure drops but rises in the W pacific
    - Trade winds weaken
    - Upwelling in E Pacific is reduced
    - Warmer waters - increased rainfall in Peru
- Global warming has amplified the intensity, duration, and frequency of 
  extreme heat and heat waves. 
* 09.11.20
- Northern latitudes experience greater seasonality in CO2 concentrations
  - This is due to variation in photosynthetic activity by plants
- Greenhouse effect
  - Some incoming solar radiation is absorbed
  - Other amounts are reflected back into the atmosphere
  - Greenhouse gases capture and reradiate some heat over and over, warming the Earth
  - More gases, more heat
- Albedo: measure of the reflectivity of a surface
  - light surfaces have a higher albedo, darker surfaces have a lower albedo
  - surfaces with a low albedo release more heat into the atmosphere
- Positive Feedback Loops
  - applied to albedo:
  - temps rise -> more ice melting -> more water warming -> temps rise
- Urban Heat Island Effect
  - cities will be inc their population, inc energy and temperature
  - cities in particular have higher temperatures
  - tree cover -> cooler temperatures
- Small changes in overall global temp can cause significant changes
  in weather creating more extreme storms and more record temps
  - roughly twice as many heat records
  - alterations in global jet streams
  - frost comes later and begins earlier
- General climate change impacts:
  - Health impacts
  - Crop productivity
  - Coastal erosion
  - Biodiversity
  - Water availability
  - Fire risk
- Weather events getting more extreme with
  - sea levels
  - wildfires
- Need both adaptation and mitigation
  - adaptation: responding to warming that has already happened
  - mitigation: preventing further warming by addressing climate change causes
* 09.09.20
** The Earth's Atmoshphere
- Climate change is a serious environmental problem impacting species, ecosystems, and the globe
- The atmosphere helps protect the Earth from the sun and keeps the temperature of the Earth cool
- Atmosphere has a significant impact on climate
- Earth's Atmosphere Composition
  - Nitrogen (78%)
  - Oxygen (21%)
  - Other - Greenhouse Gases (1%)
** The Keeling Curve
- 
* 09.02.20
** Demographic Transition Model
- Demographers use age structure diagrams to predict future growth potential of a population
  - Pyramid structures indicate fast growth
  - House-shaped structures have moderate growth
  - Diamond structures have low/negative growth
- Development leads to smaller families
- Demographic transitions happen country by country
- Industrialization might not lead to a demographic transition in all countries
  - May not be linked to quality of life
  - Religion/Cultural beliefs
  - Social justice issue, improving the well-being of women and children key to dec. fertility
** Social Justice: Education for Women
- Education of girls & economic opportunities for women are correlated with lower birth rates
- Education empowers women to take control over thri own fertility through: 
  - Birth control
  - Marrying later
  - Delaying childbirth for career opportunities
- Women earning more money is correlated to lower child mortality
** Environmental Impact
- Slowing population growth is critical to sustainability and reducing our population impact
- Our impact on the population is a result of (1) our population size and
 (2) our consumption habits - both must be addressed
- Ecological footprint: the land area needed to provide the resources for, and assimilate
  the waste of, a person or population
** Sustainability
- A dynamic process between the economy, society, and environment
- Sustainable: The process or the activity can be mantained without exhaustion or collapse
  - Intra & Inter-generational issue
  - Capacity of a system to accomodate changes:
    - rates of renewable resource use should not exceed regeneration rate
    - rates of non-renewable resource use should not exceed rate of renewable substitute dev
    - rates of pollution should not exceed ssimilative capacity of the environment
- Sustainable development has three factors:
  - Social equity
  - Economic efficiency
  - Environmental responsibility
** Worldviews
- Culture influences our beliefs through:
  - Knowledge
  - Beliefs
  - Values
  - Learned ways of life
- Worldviews are affected by: 
  - Environmental Ethics
* 08.31.20
** Human Populations
- 3 major sparks of growth
  - Agricultural Revolution
  - Industrual Revolution
  - Green Revolution
- With more food and technology, the population and need for more human labor increased
- The human population is rapidly increasing and the impact of humans is due to:
  - More humans overall
  - Greater growth / person
- To address population growth, we need to pursue a variety of approaches that address factors
  encouraging high birth rates
- Zero population growth: the absence of population growth, occurs when birth rates = death rates
  - Replacement fertility is reached
** Population Ecology
- Analyze and categorize human populations using population ecology techniques
- Population Ecology: a branch of biology dealing with the number of individuals
  in a particular species in an area over time
- Ecologists study populations to understand what makes them survive and thrive
- Size, distribution, and growth rate is influenced by a variaty of factors and are important to 
  understanding popilation ecology
** Monitoring Population Dynamics
- Population Dynamics: Changes over time in population size and composition
- Important metrics:
  - Minimum viable population - min number of individuals that would still allow population to persist or grow
  - Carrying Capacity (K) - the maximum population size that a particular environment can support indefinitely
- Population Density - the overall desnity a particular populaiton can sustain
** Exponential Growth & Populations
- Exponential growth occurs in populations when growth is unrestricted. This is, overall, unsustainable
- Growth which becomes progressively larger each breeding cycle
- Produces a J curve when plotted
** Monitoring Population Growth
- Population growth rate - the rate at which a population of a species grows over time
- Growth factors - factos which assist in the growth of a population
- Resistance factors - factors which inhibit the growth of a population
- Limiting factos: resources needed for survival but that may be in short supply
** Logistic Growth
- Occurs when a population nears carrying capacity (k) 
  - Maximum sustainable population size
  - Determined by limiting factors
** Density-dependent/ Density-independent Factors
- Density dependent factors increase as populations grow, typically biotic
  - Disease
  - Competition
  - Predation
- Density independent facts affect population growth regardless of population size
  - Storm
  - Fire/Flood
  - Avalanche
** Regulation
- Tendency for populations to decrease in size when above acertain level, and increase
  in size below that level
- Populations can only be regulated by density-dependent factors
- Top down Regulation
  - Predation
  - Disease
- Bottom up Regulation
  - Nutrients
  - Water
  - Sunlight
* 08.28.20
** What is Science?
- Science: a body of knowledge that allows us to understand the world around us
- Science is based on empirical evidence
- Science allows us to test our ideas and evaluate the evidence
- Scientific knowledge, including facts, theories, and laws, is subject to change
- Scientific claims change as new evidence is made available
** White-Nose Syndrome Case Study
*** About WNS
- White-Nose Syndrome
  - 2007-2016, 6+ million bats dead as a result of White Nose Syndrome
  - The reason for the deaths was White-Nose Syndrome
- Chytridiomycosis
  - Infectious, fungal disease affecting amphibians
  - Helped understand white-nose syndrome with bats
*** Science with WNS
- Scientific Method: the procedure used to empirically test a hypothesis
  1. Observations generate questions
  2. Choose a question to investigate
  3. Consult literature
  4. Develop a hypothesis and make a testable prediction
  5. Design and carry out a study
  6. Analyze data
  7. Draw a conclusion
- Inferences: Conclusions drawn based on observations
- Hypothesis: An inference that proposes possible explanation that includes previous knowledge/observation
- Testing a Hypothesis: Hypotheses can be tested through an observational or experimental study
- Scientific Studies: A fair test with results that could support or falsify the research prediction
  - Experimental Studies: Conditions are manipulated intentionally
    - Test Group: the group in an experimental study such that it differs from the control in only one way
    - Control Group: the group in an experimental study to which the test group's results are compared 
  - Observational Studies: Gather real-world data without any intentional variable manipulation
- Theory: A hypothesis that survives repeated testing by significant research can become a theory
- Correlation v Causation
  - Correlation: two things occuring together but not necessarily having a cause-effect relationship
  - Cause-Effect Relationship: the associationof a two variables that identifies one variable occurring
    as a result of the other
  - Observational studies can derive correlation but not causation
  - Experimental studies can derive causational relationships
- Policy: a formalized plan that addresses a desired outcome or goal
  - policies need to be flexible, adapt to new findings, address the environmental problem, fit social need
    and be economically viable in order to work effectively.
** Summary
- Scientific knowledge, through reliable and durable, is never absolute pr certain
- This knowledge, including facts, theories, and laws, is subject to change
- Physical evidence, systematically collected and logically analyzed, helps scientists
  understand environmental issues and guide policy decisions
* 08.25.20
** Applied v Empirical Science
- Applied Science = research whose findings are used to solve practical problems
- Empirical science: A scientific approach that investigates the natural world through case studies
** Social Traps
- Occurs when a large amount of people are using a shared resource
- Seem good in the short term but are actually bad in the long term
- 3 Types:
  - Tragedy of the Commons: When resources are shared, individuals try to maximize personal
    benefit which hurts the resource itself
  - Time delay: Collective decisions that are good today but gone tomorrow
  - Sliding reinforcer: related to the evolution of natural organisms and GMOs
** Beginning with Data Interpretation 
- Variables represent factors that can be manipulated, controlled, or merely measured for research
- Variation = how much a variable changes
- Independent var is controlled to see effects in the Dependent var
- Graphs explore relationships with data and report this data
** Observational v Experimental Studies
- Observational studies can observe a correlation but are unable to derive a causational reln.
- Experimental studies have a control var (required) and are able to derive causactional rlns.
* 08.24.20
** Definitions
- Ecology: the branch of science dealing with the relationships of living things to one another & the environment
- Environmental Science: The study of all aspects of the environment, including physical, chemical, and biological factos, particularly with respect to how these aspects affect humans, and vice versa
- Environmental Ethics: Personal philosophy that influences how a person interacts with their natural environment and thus influences how one responds to environmental problems
** Ecology != Environmentalism
- Distinguish between envrironmentalism & ecology

| Environmentalism                    | Ecology                                          |
|-------------------------------------+--------------------------------------------------|
| Activism to protect the environment | Scientific study of living and non-living things |
