* 10.09.20
Donald Trump, during his time as president of the United States has upheld American democracy by abiding by the systems of checks and balances in the branches of government and actively contributing to passing policy that he promised during the 2016 election cycle. Democracies are based largely upon governments following the will of the people and the argument can be made that when Donald Trump was elected in 2016, the people wanted the policies he promised.
* Module 8
** Developed Democracies
- Post-modern or post-material values: values things more than just the ability to live
  from day to day; Increasing quality of life through high mass consumption and self-
  acutalization
- Began and most prevalent in Europe, least prevalent in Africa w NA,SA in between
- Economic development often supports democratic development but does not always relate
- Human Development Index shows that just because a country is rich doesn't mean wealth
  is evenly distributed
- Gini Index can be used to show inequality, Social democracies have low gini scores
  - US is an anomaly here
  - COVID shows that death rate is extremely low for mercantile democracy
** The EU & Germany
*** History of the EU
- Began as the European Coal and Steel Community (1951)
- Started with France, Germany, Italy, Benelux
- Added European Economic Community & European Atomic Energy Community (1957) Treaty of Rome
- Brought the whole thing together with the Single European Act (1986)
- Single European Act -> Maastrict Treaty (1991)
- EU declared (1993)
- Currently 27 member states
*** Structure of the EU
- European Council - heads of govt of each member
- Council of the EU - Main legislative body, crafts legislation and budget w parliament
- EU Parliament - elected by citizens of respective member states, shares duties w council
- Court of Justice of the EU - hears cases brought by/against member states, EU citizens, companies, etc.
- Court of Auditors - controls EU budget
- European Central Bank - forms EU econ and monetary policy, manages Euro
*** Germany & The EU
- Largest pop of EU members
- Highest GDP of EU members
- Second highest employment rate, third lowest unemployment rate with a national min wage
* Module 7
** Comparing the US & UK
| UK                                          | US                            |
| Parliamentary system                        | Presdential system            |
| Single Member District Majoritarian System  | SMD + Majoritarian system     |
| No single written constitution              | constitution est. 1787        |
| Limited local govt. some devolved authority | Federal system w state powers |
| 3 Branches of Govt. + Crown (Ceremonial)    | 3 Branches of gove            |
| No checks and balances, sep. of powers      | Sep. of powers                |
| House of Commons, House of Lords            | House of Rep, Senate          |
- Both are democracies
* Module 6
** Democratic Institutions
*** Legislatures
- Forum for national political Debate
- Where laws are proposed or passed
- Bicameral (two houses)
  - Senate & House in US
   - House of Lords & Commons in the UK
- Unicameral
  - Single house more likely to be found in smaller and more centralized democracies
  - Sfound in Norway, South Koera
*** Judiciary
- Central to democracy's rule of law
- Different types of courts and organizations of courts
- Some countries have a constitutional court solely to interpret constitutional legality,
  this is shown through judicial review
- Not all countries have a supreme court that exercises judicial review
*** Executvies
 - Head of State
  - Represents the government on the national/intl stage, mainly symbolic
- Head of Government
  - Focuses on policy-making
- President of the US is both head of state and government
- Types of Executive systems
  - Parliamentary
  - Presidential
  - Semi-Presidential
| Presidential                              | Parliamentary                         |
| Limited government (Separation of powers) | High policy-making efficiency         |
| Checks and Balances -> Gridlock           | Fusion of divisions != Gridlock       |
| Popularly-elected executive               | Executive: leader of largest party    |
| Fixed terms, no long term grip            | Parties can hold power for long times |
| Elections are candidate-based             | Single party loyalty (?)              |
** Electoral Systems
*** Single-member District (SMD)
- Also called the "first past the post" or "winner take all" system
- Voting for candidates directly instead of for a party
- Most likely to result in a two-party system
  - Called Duverge's Law
*** Proportional Representation (PR)
- Made of multi-member districts (mmd) - more than 1 person elected from ea. electoral district
- People vote for parties moreso than individuals
- Votes are ranked for parties
- Proportion of the vote for a particular party wins the party certain amounts of seats
- Tends to result in multiple parties winning seats, generally leading to electoral thresholds
*** Mixed Electoral Systems
- A comboination of SMD and PR systems
- Ranked voting
  - Alternative Vote - Australia
  - Single Transferrable Vote - Ireland
*** Referenda and Initiatives
- Some countries put political decisions in the hand of the people through a referendum
- Can be seen as a cop-out by legislators and executives back to the people
- Referenda can also be constitutionally-mandated as in Ireland
- Initiatives are political decisions put to the people due to a petition
- Certain number of people need to sign a petition before a vote
* Module 5
** Political Economy
- Political Economy: The study of how politics and economics are related
- Components:
  - Markets
  - Property
  - Public goods
  - Taxation
  - Fiscal Policy
  - Regulation
  - Trade
- Public Goods & Social ExpendituresL
  - Public goods: Those goods provided or secured by the state and are available for everyone
  - Social expenditure: The state's provision of public benefits or welfare
    - All states have some kind of social expenditure
- Taxation
  - Mostly needed to fund state activities
  - Different kinds of taxes at different levels
  - Some countries provide goods and services mostly from revenues from taxation
- Regulations
  - Rules or orders that set the boundaries of a given procedure
  - Costs of compliance
  - Costs of monitoring
  - Costs of non-compliance
- Trade & Economic Development
  - Free Trade: Trade among countries wherein no country restricts trade from any other country
    - by levying import tariffs/duties
    - through imposition of quotas
    - by providing subsidies to its own domestic firms
    - by introducing other non-tariff barriers
  - Trade that is free from barriers is theorized to improve economic development/innovaiton
    through the use of a comparative advantage
** Varieties of Capitalism
- Advantages of market systems
  - very dynamic
  - high levels of productivity
- Disadvantages of market systems
  - Variability
  - Negative market swings can ahve a domino effect
  - Negative social externalities (inequality, unemployment, etc)
- Political-Economic Systems
  - Liberal Democracy
  - Social Democracy
  - Mercantile Democracy
  - Communism
- Liberal Democracy: An ideology and political system that favors limited state role in society 
  and the economy and places a high priorty on individual political and economic freedom
- Social Democracy: A political-economic system where freedom and equality are balanced through 
  state management of economy and provision of social expenditures
  - features corporatism where government, forms, and workers have a tripartite relationship
  - often called a coordinated market economy
- Mercantile Democracy: State controls economy
  - State owns parts or all of industry
  - Heavy regulations, tariffs, and non-tariff barriers to foster and protect domestic industry
  - Little social expenditure, low taxes
  - Allows for rapid economic growth (Asian TIGER countries) and often export oriented
- No single type of democracy is better than another- some simply align with certain interests
* Module 4
** Nations & Society
- Goals of nation-building:
  - Capacity
  - Legitimacy
  - Identity
- Society: "A collection of people bound by shared institutions that define how relations
  should be conducted
- Types of Identity:
  - Primordial (genetic)
  - Ascribed (given by others)
  - Socially constructed (develops over time)
- Identity is not inherently political but can be politicized
- Citizenship: An individual or group's relation to the state
- Different states have different citizenship regimes
  - Allowance of dual citizenship
  - Types of naturalization process
- Identity as an Institution
  - Identities comprise kinds of institutions
  - Identites are sticky
  - Politicization of identities increases probability of conflict
- Ethnic conflict: Conflict between ethnic groups that struggle to acheive goals
  at each other's expense
- National Conflict: Conflict in which one or more groups within a country 
  develops clear aspirations for political independence, clashing with others as a result
** Political Culture & Ideology
- Political culture is very difficult to define and is relative
  - can be considered an informal institution
  - may be rooted in culture or religion
  - developed from an early age
- Political attitudes: how one sees the operations of the state and its institutions
  - Radical, liberal, conservative, reactionary
  - Majority are around center
  - Liberal: Seek to change society through institutional adjustments
  - Constitution: Prefer continuity, resist change
  - Radicals and Reactionaries: generally outside instuitutions, may use violence
- Attitudes are relative to political culture
  - A liberal in the US = a conservative in France
- Political ideologies: what one views as the fundamental goals of politics
  - Communism -> Social Democracy -> Liberalism -> Fascism -> Anarchy
  - Here, liberalism supports political choice, not political attitudes
  - Social democracy supports greater state intervention
  - Communism, Facsism, and Anarchy are non-democratic (radical or reactionary)
- Socialist definition
  - Communist parties of the former societ bloc (non-democratic) described as socialist
  - Nazi (extreme right) stood for national socialist party
  - Social democrat parties of advanced democracies are democratic
* 09.02.20
** State Development
- Europe v the New World
  - Compare the state development of European, "old-world" countries and "new world" countries"
    - Old world countries tend to be more imperialistic while new countries have a common exp
      of being colonies
    - New world countries were composed of different types of people while 
      Old world countries had a shared history
- Feudalism: Geographic proximity and increasing power of feudal lords -> challenges between 
  feudal properties were likely, so organization of resources and capabilities was key to survival
- Feudalism led to increased collectivism, translating to:
  - large, active labor organizations
  - large, state-provided social welfare
  - emphasis on production of higher quality goods instead of new innovation
* Module 3
** Institutions and States
*** Institutions
- Institution: Institutions are formal and informal rules 
  that structure the relationship among individuals
- Can have legal or social forces
- Institutions are resistant to change but can change as a 
  - response to outside forces
  - response to internal pressures
  - response to effects of other institutions
*** The State
- An organization that maintains a legitimate monopoly of force over a certain territory
  and its population
- A set of political institutions sets policies for the territory and its population
- Sovereignty: The ability for a state to carry out actions/policies within a territory
  independently from external actors or internal rivals/challengers
- Issues of autonomy and capcity: 
  - Autonomy: the ability for the state to weild its power independently of the public
  - Capacity: the ability for the state to accrue and utilize sufficient resources to carry out
    basic tasks and responsibilities
*** Definitions
**** General
- State: governing structur's legitimate expression of sovereignty/main political organization 
  of a country
- Regime: Informal institutions that guide how a state operates
- Government: Collection of actors in charge of carrying out political decisions of the regime
  and in the interest of the state
- Country: More generic; refers to the political collectivity of a soverieng territory
- Nation: Refers to a group of people bound together by some trait who seek to establish 
  to establish and express political interests
- Nation != Country
**** Strength of States
- Institutional Capabilities
  - Strong States: Has good institutional foundations; these institutions function well
  - Weak States: Does not have good institutional foundations, its institutions do not function well 
  - Failed States: Institutions so weak that they basically collapse and have no sovereignty
- Organizational Structure
  - Strong states maintain a fair amonut of centralized control
  - Weak states hand down authority to local institutions and are decentralized
** Legitimacy & Sovereignty
- Legitimacy: a value whereby something or someone is recognized and accepted by a large 
  portion of the population as right and proper (is highly subjective)
- Types of legitimacy:
  - Traditional legitimacy: embodies historical myths/legends and continues from past to present
  - Charismatic legitimacy: Built on the force of ideas and appeals embodied by a leader
  - Rational-Legal legitimacy: Based on a system of laws and procedures that are institutionalized
- Sources of Legitimacy:
  - Conferred by the ruler to a ruler, government, or state
  - Ascribed to a state or ruler by other states or rulers (prerequisity for intl. cooperation)
  - Ascribed to a state or ruler by organizations/non-state actors
- Legitimacy can often be used to push for change
* 08.26.20
** Defining a Good Society
- Although observable, empirical assessments may differ from person to person,
  depending upon factors that may distort individual observation.
- Multiple factors contribute to whether a society is "good" or not, critical to comparing countries and 
  political systems
* Module 2
** Video 1
*** "Traditional Approach"
- Focus on a "formal-legal" aspects of political institutions
- Mostly a categorizing exercise with little analysis
- Many European ex-pats were these scholars
*** Modern Era (1960s-1980s)
- Scholars stop describing, start comparing
- Behavioral Revolution - emphasis on individual, group behavior, not static institutions
- Gave rise to "developmentalism" or "modernization theory" 
  - Proposed that a state develops economically, political and social development follows
  - Functionalism (functions of differently societal elements lay foundation for growth)
*** Development (1960s-1980s)
- 5 stages each society goes through for development:
- Traditional society (no mass production)
- Preconditions for economic take-off (advent of industrialization and mass production)
- Take-off (dynamic economic growth) 
- Drive to maturity (long era of econ growth, modern tech usage)
- Age of high mass consumption (everyon is within driving distance of McDonalds (most places))
*** Critiques of Behavioralims/Developmentalism
- Enthocentric and ideologically driven
- Creates dependency: capitalism creates a situation where underdeveloped countries depend
  on developed countries
- Developmentalist theories tried to be a one-size-fit-all theory which wasn't bale to be applied
  to all individual case studies
*** Post-Behavioralism (1990s-Present)
- Development of middle-range theories instead of one single theory
- Diversity of approaches (qualitative, quantitative, case sudies)
- Takes culture and historical context into consideration
- Rational choice theory applied
- Political economy: the state can have a varying role in economic matters
*** New Institutionalism (Past 25 years)
- Institutions are the nexus of political action
- Institutions are dynamic that interact over time w other variables
- Institutions comprise the surrounding environment & sentiment

** Video 2
*** The Study of Comparative Politics
- Comparative politics implies a method of study or an approach to an analysis, not a single theory
- greatest challenge is that events occur in real time with unreplicable environments
- events in politics can not be replicated to test for validity
*** Goals
- Goal: To assess which factors cause a certain outcome by comparing or contrasting cases
- Cases: One of the group of things (events, states, actors, etc.) to be studied
- Variable: a factor that changes over time or in different cases
  - Independent var: causal var
  - Dependent var: outcome var
- Causal relationships can be shown as:
  - Cause -> effect
  - Independent var -> dependent var
  - Explanators var -> outcome
  - x var -> y var
- Hypothesis: a possible answer that explains a causal effect
*** Challenges
- Goal: to determine causality, not just correlation

- In comparative politics, the researcher may not be able to:
  - have a constant
  - measure certain variables
  - anticipate certain events
  - disentangle one variable from others
  - Access to cases & information
    - Langauage barriers
    - Time & funding
    - Sufficient cases (and selection bias)
    - IRB (Institutional Review Board)
- Correlation: when var A occurs with var B, one is not caused by the other
- Endogeneity: when it cannot be determined whether an outcome was caused by another factor
    or the outcome caused that factor to occur    
** Video 3
*** Most Similar Systems Design (MSS)
- A method in which as many independent vars as possible are held constant to explain a political
  outcome: similar cases, different outcomes can help isolate a variable
- Special Variation of MSS: Within-Case Comparison
  - Single case analyzed over time or in different geographical areas
  - Breaks up a single case into subparts and allows for comparison
*** Most-Different Systems Design (MDS)
- Looks at cases that are different from one another and observes why the same political outcome is
  observed as a method of understanding how to isolate a single causal variable
*** Overview
- Probable causal explanations (hypotheses): goal of these comparative approaches
- Theories can be built from the strongest hypothesis
- Theories can further be generalized based on the case
